// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sui/rpc/v2/epoch.proto

// Protobuf Java Version: 3.25.3
package sui.rpc.v2;

public final class EpochOuterClass {
  private EpochOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EpochOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sui.rpc.v2.Epoch)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 epoch = 1;</code>
     * @return Whether the epoch field is set.
     */
    boolean hasEpoch();
    /**
     * <code>optional uint64 epoch = 1;</code>
     * @return The epoch.
     */
    long getEpoch();

    /**
     * <pre>
     * The committee governing this epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
     * @return Whether the committee field is set.
     */
    boolean hasCommittee();
    /**
     * <pre>
     * The committee governing this epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
     * @return The committee.
     */
    sui.rpc.v2.Signature.ValidatorCommittee getCommittee();
    /**
     * <pre>
     * The committee governing this epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
     */
    sui.rpc.v2.Signature.ValidatorCommitteeOrBuilder getCommitteeOrBuilder();

    /**
     * <pre>
     * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
     * beginning of the epoch, for past epochs, or the current state for the
     * current epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
     * @return Whether the systemState field is set.
     */
    boolean hasSystemState();
    /**
     * <pre>
     * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
     * beginning of the epoch, for past epochs, or the current state for the
     * current epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
     * @return The systemState.
     */
    sui.rpc.v2.SystemStateOuterClass.SystemState getSystemState();
    /**
     * <pre>
     * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
     * beginning of the epoch, for past epochs, or the current state for the
     * current epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
     */
    sui.rpc.v2.SystemStateOuterClass.SystemStateOrBuilder getSystemStateOrBuilder();

    /**
     * <code>optional uint64 first_checkpoint = 4;</code>
     * @return Whether the firstCheckpoint field is set.
     */
    boolean hasFirstCheckpoint();
    /**
     * <code>optional uint64 first_checkpoint = 4;</code>
     * @return The firstCheckpoint.
     */
    long getFirstCheckpoint();

    /**
     * <code>optional uint64 last_checkpoint = 5;</code>
     * @return Whether the lastCheckpoint field is set.
     */
    boolean hasLastCheckpoint();
    /**
     * <code>optional uint64 last_checkpoint = 5;</code>
     * @return The lastCheckpoint.
     */
    long getLastCheckpoint();

    /**
     * <code>optional .google.protobuf.Timestamp start = 6;</code>
     * @return Whether the start field is set.
     */
    boolean hasStart();
    /**
     * <code>optional .google.protobuf.Timestamp start = 6;</code>
     * @return The start.
     */
    com.google.protobuf.Timestamp getStart();
    /**
     * <code>optional .google.protobuf.Timestamp start = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getStartOrBuilder();

    /**
     * <code>optional .google.protobuf.Timestamp end = 7;</code>
     * @return Whether the end field is set.
     */
    boolean hasEnd();
    /**
     * <code>optional .google.protobuf.Timestamp end = 7;</code>
     * @return The end.
     */
    com.google.protobuf.Timestamp getEnd();
    /**
     * <code>optional .google.protobuf.Timestamp end = 7;</code>
     */
    com.google.protobuf.TimestampOrBuilder getEndOrBuilder();

    /**
     * <pre>
     * Reference gas price denominated in MIST
     * </pre>
     *
     * <code>optional uint64 reference_gas_price = 8;</code>
     * @return Whether the referenceGasPrice field is set.
     */
    boolean hasReferenceGasPrice();
    /**
     * <pre>
     * Reference gas price denominated in MIST
     * </pre>
     *
     * <code>optional uint64 reference_gas_price = 8;</code>
     * @return The referenceGasPrice.
     */
    long getReferenceGasPrice();

    /**
     * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
     * @return Whether the protocolConfig field is set.
     */
    boolean hasProtocolConfig();
    /**
     * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
     * @return The protocolConfig.
     */
    sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig getProtocolConfig();
    /**
     * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
     */
    sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfigOrBuilder getProtocolConfigOrBuilder();
  }
  /**
   * Protobuf type {@code sui.rpc.v2.Epoch}
   */
  public static final class Epoch extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sui.rpc.v2.Epoch)
      EpochOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Epoch.newBuilder() to construct.
    private Epoch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Epoch() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Epoch();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sui.rpc.v2.EpochOuterClass.internal_static_sui_rpc_v2_Epoch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sui.rpc.v2.EpochOuterClass.internal_static_sui_rpc_v2_Epoch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sui.rpc.v2.EpochOuterClass.Epoch.class, sui.rpc.v2.EpochOuterClass.Epoch.Builder.class);
    }

    private int bitField0_;
    public static final int EPOCH_FIELD_NUMBER = 1;
    private long epoch_ = 0L;
    /**
     * <code>optional uint64 epoch = 1;</code>
     * @return Whether the epoch field is set.
     */
    @java.lang.Override
    public boolean hasEpoch() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 epoch = 1;</code>
     * @return The epoch.
     */
    @java.lang.Override
    public long getEpoch() {
      return epoch_;
    }

    public static final int COMMITTEE_FIELD_NUMBER = 2;
    private sui.rpc.v2.Signature.ValidatorCommittee committee_;
    /**
     * <pre>
     * The committee governing this epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
     * @return Whether the committee field is set.
     */
    @java.lang.Override
    public boolean hasCommittee() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The committee governing this epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
     * @return The committee.
     */
    @java.lang.Override
    public sui.rpc.v2.Signature.ValidatorCommittee getCommittee() {
      return committee_ == null ? sui.rpc.v2.Signature.ValidatorCommittee.getDefaultInstance() : committee_;
    }
    /**
     * <pre>
     * The committee governing this epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
     */
    @java.lang.Override
    public sui.rpc.v2.Signature.ValidatorCommitteeOrBuilder getCommitteeOrBuilder() {
      return committee_ == null ? sui.rpc.v2.Signature.ValidatorCommittee.getDefaultInstance() : committee_;
    }

    public static final int SYSTEM_STATE_FIELD_NUMBER = 3;
    private sui.rpc.v2.SystemStateOuterClass.SystemState systemState_;
    /**
     * <pre>
     * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
     * beginning of the epoch, for past epochs, or the current state for the
     * current epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
     * @return Whether the systemState field is set.
     */
    @java.lang.Override
    public boolean hasSystemState() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
     * beginning of the epoch, for past epochs, or the current state for the
     * current epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
     * @return The systemState.
     */
    @java.lang.Override
    public sui.rpc.v2.SystemStateOuterClass.SystemState getSystemState() {
      return systemState_ == null ? sui.rpc.v2.SystemStateOuterClass.SystemState.getDefaultInstance() : systemState_;
    }
    /**
     * <pre>
     * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
     * beginning of the epoch, for past epochs, or the current state for the
     * current epoch.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
     */
    @java.lang.Override
    public sui.rpc.v2.SystemStateOuterClass.SystemStateOrBuilder getSystemStateOrBuilder() {
      return systemState_ == null ? sui.rpc.v2.SystemStateOuterClass.SystemState.getDefaultInstance() : systemState_;
    }

    public static final int FIRST_CHECKPOINT_FIELD_NUMBER = 4;
    private long firstCheckpoint_ = 0L;
    /**
     * <code>optional uint64 first_checkpoint = 4;</code>
     * @return Whether the firstCheckpoint field is set.
     */
    @java.lang.Override
    public boolean hasFirstCheckpoint() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 first_checkpoint = 4;</code>
     * @return The firstCheckpoint.
     */
    @java.lang.Override
    public long getFirstCheckpoint() {
      return firstCheckpoint_;
    }

    public static final int LAST_CHECKPOINT_FIELD_NUMBER = 5;
    private long lastCheckpoint_ = 0L;
    /**
     * <code>optional uint64 last_checkpoint = 5;</code>
     * @return Whether the lastCheckpoint field is set.
     */
    @java.lang.Override
    public boolean hasLastCheckpoint() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint64 last_checkpoint = 5;</code>
     * @return The lastCheckpoint.
     */
    @java.lang.Override
    public long getLastCheckpoint() {
      return lastCheckpoint_;
    }

    public static final int START_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp start_;
    /**
     * <code>optional .google.protobuf.Timestamp start = 6;</code>
     * @return Whether the start field is set.
     */
    @java.lang.Override
    public boolean hasStart() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp start = 6;</code>
     * @return The start.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getStart() {
      return start_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : start_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp start = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getStartOrBuilder() {
      return start_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : start_;
    }

    public static final int END_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp end_;
    /**
     * <code>optional .google.protobuf.Timestamp end = 7;</code>
     * @return Whether the end field is set.
     */
    @java.lang.Override
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp end = 7;</code>
     * @return The end.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getEnd() {
      return end_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : end_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp end = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getEndOrBuilder() {
      return end_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : end_;
    }

    public static final int REFERENCE_GAS_PRICE_FIELD_NUMBER = 8;
    private long referenceGasPrice_ = 0L;
    /**
     * <pre>
     * Reference gas price denominated in MIST
     * </pre>
     *
     * <code>optional uint64 reference_gas_price = 8;</code>
     * @return Whether the referenceGasPrice field is set.
     */
    @java.lang.Override
    public boolean hasReferenceGasPrice() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * Reference gas price denominated in MIST
     * </pre>
     *
     * <code>optional uint64 reference_gas_price = 8;</code>
     * @return The referenceGasPrice.
     */
    @java.lang.Override
    public long getReferenceGasPrice() {
      return referenceGasPrice_;
    }

    public static final int PROTOCOL_CONFIG_FIELD_NUMBER = 9;
    private sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig protocolConfig_;
    /**
     * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
     * @return Whether the protocolConfig field is set.
     */
    @java.lang.Override
    public boolean hasProtocolConfig() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
     * @return The protocolConfig.
     */
    @java.lang.Override
    public sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig getProtocolConfig() {
      return protocolConfig_ == null ? sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.getDefaultInstance() : protocolConfig_;
    }
    /**
     * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
     */
    @java.lang.Override
    public sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfigOrBuilder getProtocolConfigOrBuilder() {
      return protocolConfig_ == null ? sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.getDefaultInstance() : protocolConfig_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, epoch_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getCommittee());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getSystemState());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt64(4, firstCheckpoint_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt64(5, lastCheckpoint_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeMessage(6, getStart());
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeMessage(7, getEnd());
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeUInt64(8, referenceGasPrice_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeMessage(9, getProtocolConfig());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, epoch_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCommittee());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSystemState());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, firstCheckpoint_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, lastCheckpoint_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getStart());
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getEnd());
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, referenceGasPrice_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getProtocolConfig());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sui.rpc.v2.EpochOuterClass.Epoch)) {
        return super.equals(obj);
      }
      sui.rpc.v2.EpochOuterClass.Epoch other = (sui.rpc.v2.EpochOuterClass.Epoch) obj;

      if (hasEpoch() != other.hasEpoch()) return false;
      if (hasEpoch()) {
        if (getEpoch()
            != other.getEpoch()) return false;
      }
      if (hasCommittee() != other.hasCommittee()) return false;
      if (hasCommittee()) {
        if (!getCommittee()
            .equals(other.getCommittee())) return false;
      }
      if (hasSystemState() != other.hasSystemState()) return false;
      if (hasSystemState()) {
        if (!getSystemState()
            .equals(other.getSystemState())) return false;
      }
      if (hasFirstCheckpoint() != other.hasFirstCheckpoint()) return false;
      if (hasFirstCheckpoint()) {
        if (getFirstCheckpoint()
            != other.getFirstCheckpoint()) return false;
      }
      if (hasLastCheckpoint() != other.hasLastCheckpoint()) return false;
      if (hasLastCheckpoint()) {
        if (getLastCheckpoint()
            != other.getLastCheckpoint()) return false;
      }
      if (hasStart() != other.hasStart()) return false;
      if (hasStart()) {
        if (!getStart()
            .equals(other.getStart())) return false;
      }
      if (hasEnd() != other.hasEnd()) return false;
      if (hasEnd()) {
        if (!getEnd()
            .equals(other.getEnd())) return false;
      }
      if (hasReferenceGasPrice() != other.hasReferenceGasPrice()) return false;
      if (hasReferenceGasPrice()) {
        if (getReferenceGasPrice()
            != other.getReferenceGasPrice()) return false;
      }
      if (hasProtocolConfig() != other.hasProtocolConfig()) return false;
      if (hasProtocolConfig()) {
        if (!getProtocolConfig()
            .equals(other.getProtocolConfig())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEpoch()) {
        hash = (37 * hash) + EPOCH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEpoch());
      }
      if (hasCommittee()) {
        hash = (37 * hash) + COMMITTEE_FIELD_NUMBER;
        hash = (53 * hash) + getCommittee().hashCode();
      }
      if (hasSystemState()) {
        hash = (37 * hash) + SYSTEM_STATE_FIELD_NUMBER;
        hash = (53 * hash) + getSystemState().hashCode();
      }
      if (hasFirstCheckpoint()) {
        hash = (37 * hash) + FIRST_CHECKPOINT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFirstCheckpoint());
      }
      if (hasLastCheckpoint()) {
        hash = (37 * hash) + LAST_CHECKPOINT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLastCheckpoint());
      }
      if (hasStart()) {
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + getStart().hashCode();
      }
      if (hasEnd()) {
        hash = (37 * hash) + END_FIELD_NUMBER;
        hash = (53 * hash) + getEnd().hashCode();
      }
      if (hasReferenceGasPrice()) {
        hash = (37 * hash) + REFERENCE_GAS_PRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getReferenceGasPrice());
      }
      if (hasProtocolConfig()) {
        hash = (37 * hash) + PROTOCOL_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolConfig().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sui.rpc.v2.EpochOuterClass.Epoch parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.EpochOuterClass.Epoch parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.EpochOuterClass.Epoch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.EpochOuterClass.Epoch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.EpochOuterClass.Epoch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.EpochOuterClass.Epoch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.EpochOuterClass.Epoch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.EpochOuterClass.Epoch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sui.rpc.v2.EpochOuterClass.Epoch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sui.rpc.v2.EpochOuterClass.Epoch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sui.rpc.v2.EpochOuterClass.Epoch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.EpochOuterClass.Epoch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sui.rpc.v2.EpochOuterClass.Epoch prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sui.rpc.v2.Epoch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sui.rpc.v2.Epoch)
        sui.rpc.v2.EpochOuterClass.EpochOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sui.rpc.v2.EpochOuterClass.internal_static_sui_rpc_v2_Epoch_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sui.rpc.v2.EpochOuterClass.internal_static_sui_rpc_v2_Epoch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sui.rpc.v2.EpochOuterClass.Epoch.class, sui.rpc.v2.EpochOuterClass.Epoch.Builder.class);
      }

      // Construct using sui.rpc.v2.EpochOuterClass.Epoch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCommitteeFieldBuilder();
          getSystemStateFieldBuilder();
          getStartFieldBuilder();
          getEndFieldBuilder();
          getProtocolConfigFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        epoch_ = 0L;
        committee_ = null;
        if (committeeBuilder_ != null) {
          committeeBuilder_.dispose();
          committeeBuilder_ = null;
        }
        systemState_ = null;
        if (systemStateBuilder_ != null) {
          systemStateBuilder_.dispose();
          systemStateBuilder_ = null;
        }
        firstCheckpoint_ = 0L;
        lastCheckpoint_ = 0L;
        start_ = null;
        if (startBuilder_ != null) {
          startBuilder_.dispose();
          startBuilder_ = null;
        }
        end_ = null;
        if (endBuilder_ != null) {
          endBuilder_.dispose();
          endBuilder_ = null;
        }
        referenceGasPrice_ = 0L;
        protocolConfig_ = null;
        if (protocolConfigBuilder_ != null) {
          protocolConfigBuilder_.dispose();
          protocolConfigBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sui.rpc.v2.EpochOuterClass.internal_static_sui_rpc_v2_Epoch_descriptor;
      }

      @java.lang.Override
      public sui.rpc.v2.EpochOuterClass.Epoch getDefaultInstanceForType() {
        return sui.rpc.v2.EpochOuterClass.Epoch.getDefaultInstance();
      }

      @java.lang.Override
      public sui.rpc.v2.EpochOuterClass.Epoch build() {
        sui.rpc.v2.EpochOuterClass.Epoch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sui.rpc.v2.EpochOuterClass.Epoch buildPartial() {
        sui.rpc.v2.EpochOuterClass.Epoch result = new sui.rpc.v2.EpochOuterClass.Epoch(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sui.rpc.v2.EpochOuterClass.Epoch result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.epoch_ = epoch_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.committee_ = committeeBuilder_ == null
              ? committee_
              : committeeBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.systemState_ = systemStateBuilder_ == null
              ? systemState_
              : systemStateBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.firstCheckpoint_ = firstCheckpoint_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.lastCheckpoint_ = lastCheckpoint_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.start_ = startBuilder_ == null
              ? start_
              : startBuilder_.build();
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.end_ = endBuilder_ == null
              ? end_
              : endBuilder_.build();
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.referenceGasPrice_ = referenceGasPrice_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.protocolConfig_ = protocolConfigBuilder_ == null
              ? protocolConfig_
              : protocolConfigBuilder_.build();
          to_bitField0_ |= 0x00000100;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sui.rpc.v2.EpochOuterClass.Epoch) {
          return mergeFrom((sui.rpc.v2.EpochOuterClass.Epoch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sui.rpc.v2.EpochOuterClass.Epoch other) {
        if (other == sui.rpc.v2.EpochOuterClass.Epoch.getDefaultInstance()) return this;
        if (other.hasEpoch()) {
          setEpoch(other.getEpoch());
        }
        if (other.hasCommittee()) {
          mergeCommittee(other.getCommittee());
        }
        if (other.hasSystemState()) {
          mergeSystemState(other.getSystemState());
        }
        if (other.hasFirstCheckpoint()) {
          setFirstCheckpoint(other.getFirstCheckpoint());
        }
        if (other.hasLastCheckpoint()) {
          setLastCheckpoint(other.getLastCheckpoint());
        }
        if (other.hasStart()) {
          mergeStart(other.getStart());
        }
        if (other.hasEnd()) {
          mergeEnd(other.getEnd());
        }
        if (other.hasReferenceGasPrice()) {
          setReferenceGasPrice(other.getReferenceGasPrice());
        }
        if (other.hasProtocolConfig()) {
          mergeProtocolConfig(other.getProtocolConfig());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                epoch_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getCommitteeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getSystemStateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                firstCheckpoint_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                lastCheckpoint_ = input.readUInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                input.readMessage(
                    getStartFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    getEndFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                referenceGasPrice_ = input.readUInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 74: {
                input.readMessage(
                    getProtocolConfigFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long epoch_ ;
      /**
       * <code>optional uint64 epoch = 1;</code>
       * @return Whether the epoch field is set.
       */
      @java.lang.Override
      public boolean hasEpoch() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 epoch = 1;</code>
       * @return The epoch.
       */
      @java.lang.Override
      public long getEpoch() {
        return epoch_;
      }
      /**
       * <code>optional uint64 epoch = 1;</code>
       * @param value The epoch to set.
       * @return This builder for chaining.
       */
      public Builder setEpoch(long value) {

        epoch_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 epoch = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEpoch() {
        bitField0_ = (bitField0_ & ~0x00000001);
        epoch_ = 0L;
        onChanged();
        return this;
      }

      private sui.rpc.v2.Signature.ValidatorCommittee committee_;
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.Signature.ValidatorCommittee, sui.rpc.v2.Signature.ValidatorCommittee.Builder, sui.rpc.v2.Signature.ValidatorCommitteeOrBuilder> committeeBuilder_;
      /**
       * <pre>
       * The committee governing this epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
       * @return Whether the committee field is set.
       */
      public boolean hasCommittee() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The committee governing this epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
       * @return The committee.
       */
      public sui.rpc.v2.Signature.ValidatorCommittee getCommittee() {
        if (committeeBuilder_ == null) {
          return committee_ == null ? sui.rpc.v2.Signature.ValidatorCommittee.getDefaultInstance() : committee_;
        } else {
          return committeeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The committee governing this epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
       */
      public Builder setCommittee(sui.rpc.v2.Signature.ValidatorCommittee value) {
        if (committeeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          committee_ = value;
        } else {
          committeeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The committee governing this epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
       */
      public Builder setCommittee(
          sui.rpc.v2.Signature.ValidatorCommittee.Builder builderForValue) {
        if (committeeBuilder_ == null) {
          committee_ = builderForValue.build();
        } else {
          committeeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The committee governing this epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
       */
      public Builder mergeCommittee(sui.rpc.v2.Signature.ValidatorCommittee value) {
        if (committeeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            committee_ != null &&
            committee_ != sui.rpc.v2.Signature.ValidatorCommittee.getDefaultInstance()) {
            getCommitteeBuilder().mergeFrom(value);
          } else {
            committee_ = value;
          }
        } else {
          committeeBuilder_.mergeFrom(value);
        }
        if (committee_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The committee governing this epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
       */
      public Builder clearCommittee() {
        bitField0_ = (bitField0_ & ~0x00000002);
        committee_ = null;
        if (committeeBuilder_ != null) {
          committeeBuilder_.dispose();
          committeeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The committee governing this epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
       */
      public sui.rpc.v2.Signature.ValidatorCommittee.Builder getCommitteeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCommitteeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The committee governing this epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
       */
      public sui.rpc.v2.Signature.ValidatorCommitteeOrBuilder getCommitteeOrBuilder() {
        if (committeeBuilder_ != null) {
          return committeeBuilder_.getMessageOrBuilder();
        } else {
          return committee_ == null ?
              sui.rpc.v2.Signature.ValidatorCommittee.getDefaultInstance() : committee_;
        }
      }
      /**
       * <pre>
       * The committee governing this epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.ValidatorCommittee committee = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.Signature.ValidatorCommittee, sui.rpc.v2.Signature.ValidatorCommittee.Builder, sui.rpc.v2.Signature.ValidatorCommitteeOrBuilder> 
          getCommitteeFieldBuilder() {
        if (committeeBuilder_ == null) {
          committeeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sui.rpc.v2.Signature.ValidatorCommittee, sui.rpc.v2.Signature.ValidatorCommittee.Builder, sui.rpc.v2.Signature.ValidatorCommitteeOrBuilder>(
                  getCommittee(),
                  getParentForChildren(),
                  isClean());
          committee_ = null;
        }
        return committeeBuilder_;
      }

      private sui.rpc.v2.SystemStateOuterClass.SystemState systemState_;
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.SystemStateOuterClass.SystemState, sui.rpc.v2.SystemStateOuterClass.SystemState.Builder, sui.rpc.v2.SystemStateOuterClass.SystemStateOrBuilder> systemStateBuilder_;
      /**
       * <pre>
       * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
       * beginning of the epoch, for past epochs, or the current state for the
       * current epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
       * @return Whether the systemState field is set.
       */
      public boolean hasSystemState() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
       * beginning of the epoch, for past epochs, or the current state for the
       * current epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
       * @return The systemState.
       */
      public sui.rpc.v2.SystemStateOuterClass.SystemState getSystemState() {
        if (systemStateBuilder_ == null) {
          return systemState_ == null ? sui.rpc.v2.SystemStateOuterClass.SystemState.getDefaultInstance() : systemState_;
        } else {
          return systemStateBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
       * beginning of the epoch, for past epochs, or the current state for the
       * current epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
       */
      public Builder setSystemState(sui.rpc.v2.SystemStateOuterClass.SystemState value) {
        if (systemStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          systemState_ = value;
        } else {
          systemStateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
       * beginning of the epoch, for past epochs, or the current state for the
       * current epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
       */
      public Builder setSystemState(
          sui.rpc.v2.SystemStateOuterClass.SystemState.Builder builderForValue) {
        if (systemStateBuilder_ == null) {
          systemState_ = builderForValue.build();
        } else {
          systemStateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
       * beginning of the epoch, for past epochs, or the current state for the
       * current epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
       */
      public Builder mergeSystemState(sui.rpc.v2.SystemStateOuterClass.SystemState value) {
        if (systemStateBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            systemState_ != null &&
            systemState_ != sui.rpc.v2.SystemStateOuterClass.SystemState.getDefaultInstance()) {
            getSystemStateBuilder().mergeFrom(value);
          } else {
            systemState_ = value;
          }
        } else {
          systemStateBuilder_.mergeFrom(value);
        }
        if (systemState_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
       * beginning of the epoch, for past epochs, or the current state for the
       * current epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
       */
      public Builder clearSystemState() {
        bitField0_ = (bitField0_ & ~0x00000004);
        systemState_ = null;
        if (systemStateBuilder_ != null) {
          systemStateBuilder_.dispose();
          systemStateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
       * beginning of the epoch, for past epochs, or the current state for the
       * current epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
       */
      public sui.rpc.v2.SystemStateOuterClass.SystemState.Builder getSystemStateBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSystemStateFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
       * beginning of the epoch, for past epochs, or the current state for the
       * current epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
       */
      public sui.rpc.v2.SystemStateOuterClass.SystemStateOrBuilder getSystemStateOrBuilder() {
        if (systemStateBuilder_ != null) {
          return systemStateBuilder_.getMessageOrBuilder();
        } else {
          return systemState_ == null ?
              sui.rpc.v2.SystemStateOuterClass.SystemState.getDefaultInstance() : systemState_;
        }
      }
      /**
       * <pre>
       * Snapshot of Sui's SystemState (`0x3::sui_system::SystemState`) at the
       * beginning of the epoch, for past epochs, or the current state for the
       * current epoch.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.SystemState system_state = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.SystemStateOuterClass.SystemState, sui.rpc.v2.SystemStateOuterClass.SystemState.Builder, sui.rpc.v2.SystemStateOuterClass.SystemStateOrBuilder> 
          getSystemStateFieldBuilder() {
        if (systemStateBuilder_ == null) {
          systemStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sui.rpc.v2.SystemStateOuterClass.SystemState, sui.rpc.v2.SystemStateOuterClass.SystemState.Builder, sui.rpc.v2.SystemStateOuterClass.SystemStateOrBuilder>(
                  getSystemState(),
                  getParentForChildren(),
                  isClean());
          systemState_ = null;
        }
        return systemStateBuilder_;
      }

      private long firstCheckpoint_ ;
      /**
       * <code>optional uint64 first_checkpoint = 4;</code>
       * @return Whether the firstCheckpoint field is set.
       */
      @java.lang.Override
      public boolean hasFirstCheckpoint() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint64 first_checkpoint = 4;</code>
       * @return The firstCheckpoint.
       */
      @java.lang.Override
      public long getFirstCheckpoint() {
        return firstCheckpoint_;
      }
      /**
       * <code>optional uint64 first_checkpoint = 4;</code>
       * @param value The firstCheckpoint to set.
       * @return This builder for chaining.
       */
      public Builder setFirstCheckpoint(long value) {

        firstCheckpoint_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 first_checkpoint = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstCheckpoint() {
        bitField0_ = (bitField0_ & ~0x00000008);
        firstCheckpoint_ = 0L;
        onChanged();
        return this;
      }

      private long lastCheckpoint_ ;
      /**
       * <code>optional uint64 last_checkpoint = 5;</code>
       * @return Whether the lastCheckpoint field is set.
       */
      @java.lang.Override
      public boolean hasLastCheckpoint() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint64 last_checkpoint = 5;</code>
       * @return The lastCheckpoint.
       */
      @java.lang.Override
      public long getLastCheckpoint() {
        return lastCheckpoint_;
      }
      /**
       * <code>optional uint64 last_checkpoint = 5;</code>
       * @param value The lastCheckpoint to set.
       * @return This builder for chaining.
       */
      public Builder setLastCheckpoint(long value) {

        lastCheckpoint_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 last_checkpoint = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastCheckpoint() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastCheckpoint_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp start_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp start = 6;</code>
       * @return Whether the start field is set.
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional .google.protobuf.Timestamp start = 6;</code>
       * @return The start.
       */
      public com.google.protobuf.Timestamp getStart() {
        if (startBuilder_ == null) {
          return start_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : start_;
        } else {
          return startBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp start = 6;</code>
       */
      public Builder setStart(com.google.protobuf.Timestamp value) {
        if (startBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          start_ = value;
        } else {
          startBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp start = 6;</code>
       */
      public Builder setStart(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (startBuilder_ == null) {
          start_ = builderForValue.build();
        } else {
          startBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp start = 6;</code>
       */
      public Builder mergeStart(com.google.protobuf.Timestamp value) {
        if (startBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            start_ != null &&
            start_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getStartBuilder().mergeFrom(value);
          } else {
            start_ = value;
          }
        } else {
          startBuilder_.mergeFrom(value);
        }
        if (start_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp start = 6;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000020);
        start_ = null;
        if (startBuilder_ != null) {
          startBuilder_.dispose();
          startBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp start = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getStartBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getStartFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp start = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStartOrBuilder() {
        if (startBuilder_ != null) {
          return startBuilder_.getMessageOrBuilder();
        } else {
          return start_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : start_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp start = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getStartFieldBuilder() {
        if (startBuilder_ == null) {
          startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStart(),
                  getParentForChildren(),
                  isClean());
          start_ = null;
        }
        return startBuilder_;
      }

      private com.google.protobuf.Timestamp end_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp end = 7;</code>
       * @return Whether the end field is set.
       */
      public boolean hasEnd() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional .google.protobuf.Timestamp end = 7;</code>
       * @return The end.
       */
      public com.google.protobuf.Timestamp getEnd() {
        if (endBuilder_ == null) {
          return end_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : end_;
        } else {
          return endBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp end = 7;</code>
       */
      public Builder setEnd(com.google.protobuf.Timestamp value) {
        if (endBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          end_ = value;
        } else {
          endBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp end = 7;</code>
       */
      public Builder setEnd(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (endBuilder_ == null) {
          end_ = builderForValue.build();
        } else {
          endBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp end = 7;</code>
       */
      public Builder mergeEnd(com.google.protobuf.Timestamp value) {
        if (endBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            end_ != null &&
            end_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getEndBuilder().mergeFrom(value);
          } else {
            end_ = value;
          }
        } else {
          endBuilder_.mergeFrom(value);
        }
        if (end_ != null) {
          bitField0_ |= 0x00000040;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp end = 7;</code>
       */
      public Builder clearEnd() {
        bitField0_ = (bitField0_ & ~0x00000040);
        end_ = null;
        if (endBuilder_ != null) {
          endBuilder_.dispose();
          endBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp end = 7;</code>
       */
      public com.google.protobuf.Timestamp.Builder getEndBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getEndFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp end = 7;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getEndOrBuilder() {
        if (endBuilder_ != null) {
          return endBuilder_.getMessageOrBuilder();
        } else {
          return end_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : end_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp end = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getEndFieldBuilder() {
        if (endBuilder_ == null) {
          endBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getEnd(),
                  getParentForChildren(),
                  isClean());
          end_ = null;
        }
        return endBuilder_;
      }

      private long referenceGasPrice_ ;
      /**
       * <pre>
       * Reference gas price denominated in MIST
       * </pre>
       *
       * <code>optional uint64 reference_gas_price = 8;</code>
       * @return Whether the referenceGasPrice field is set.
       */
      @java.lang.Override
      public boolean hasReferenceGasPrice() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * Reference gas price denominated in MIST
       * </pre>
       *
       * <code>optional uint64 reference_gas_price = 8;</code>
       * @return The referenceGasPrice.
       */
      @java.lang.Override
      public long getReferenceGasPrice() {
        return referenceGasPrice_;
      }
      /**
       * <pre>
       * Reference gas price denominated in MIST
       * </pre>
       *
       * <code>optional uint64 reference_gas_price = 8;</code>
       * @param value The referenceGasPrice to set.
       * @return This builder for chaining.
       */
      public Builder setReferenceGasPrice(long value) {

        referenceGasPrice_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Reference gas price denominated in MIST
       * </pre>
       *
       * <code>optional uint64 reference_gas_price = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearReferenceGasPrice() {
        bitField0_ = (bitField0_ & ~0x00000080);
        referenceGasPrice_ = 0L;
        onChanged();
        return this;
      }

      private sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig protocolConfig_;
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig, sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.Builder, sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfigOrBuilder> protocolConfigBuilder_;
      /**
       * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
       * @return Whether the protocolConfig field is set.
       */
      public boolean hasProtocolConfig() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
       * @return The protocolConfig.
       */
      public sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig getProtocolConfig() {
        if (protocolConfigBuilder_ == null) {
          return protocolConfig_ == null ? sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.getDefaultInstance() : protocolConfig_;
        } else {
          return protocolConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
       */
      public Builder setProtocolConfig(sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig value) {
        if (protocolConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          protocolConfig_ = value;
        } else {
          protocolConfigBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
       */
      public Builder setProtocolConfig(
          sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.Builder builderForValue) {
        if (protocolConfigBuilder_ == null) {
          protocolConfig_ = builderForValue.build();
        } else {
          protocolConfigBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
       */
      public Builder mergeProtocolConfig(sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig value) {
        if (protocolConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0) &&
            protocolConfig_ != null &&
            protocolConfig_ != sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.getDefaultInstance()) {
            getProtocolConfigBuilder().mergeFrom(value);
          } else {
            protocolConfig_ = value;
          }
        } else {
          protocolConfigBuilder_.mergeFrom(value);
        }
        if (protocolConfig_ != null) {
          bitField0_ |= 0x00000100;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
       */
      public Builder clearProtocolConfig() {
        bitField0_ = (bitField0_ & ~0x00000100);
        protocolConfig_ = null;
        if (protocolConfigBuilder_ != null) {
          protocolConfigBuilder_.dispose();
          protocolConfigBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
       */
      public sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.Builder getProtocolConfigBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getProtocolConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
       */
      public sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfigOrBuilder getProtocolConfigOrBuilder() {
        if (protocolConfigBuilder_ != null) {
          return protocolConfigBuilder_.getMessageOrBuilder();
        } else {
          return protocolConfig_ == null ?
              sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.getDefaultInstance() : protocolConfig_;
        }
      }
      /**
       * <code>optional .sui.rpc.v2.ProtocolConfig protocol_config = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig, sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.Builder, sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfigOrBuilder> 
          getProtocolConfigFieldBuilder() {
        if (protocolConfigBuilder_ == null) {
          protocolConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig, sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.Builder, sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfigOrBuilder>(
                  getProtocolConfig(),
                  getParentForChildren(),
                  isClean());
          protocolConfig_ = null;
        }
        return protocolConfigBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sui.rpc.v2.Epoch)
    }

    // @@protoc_insertion_point(class_scope:sui.rpc.v2.Epoch)
    private static final sui.rpc.v2.EpochOuterClass.Epoch DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sui.rpc.v2.EpochOuterClass.Epoch();
    }

    public static sui.rpc.v2.EpochOuterClass.Epoch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Epoch>
        PARSER = new com.google.protobuf.AbstractParser<Epoch>() {
      @java.lang.Override
      public Epoch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Epoch> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Epoch> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sui.rpc.v2.EpochOuterClass.Epoch getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sui_rpc_v2_Epoch_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sui_rpc_v2_Epoch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026sui/rpc/v2/epoch.proto\022\nsui.rpc.v2\032\037go" +
      "ogle/protobuf/timestamp.proto\032 sui/rpc/v" +
      "2/protocol_config.proto\032\032sui/rpc/v2/sign" +
      "ature.proto\032\035sui/rpc/v2/system_state.pro" +
      "to\"\216\004\n\005Epoch\022\022\n\005epoch\030\001 \001(\004H\000\210\001\001\0226\n\tcomm" +
      "ittee\030\002 \001(\0132\036.sui.rpc.v2.ValidatorCommit" +
      "teeH\001\210\001\001\0222\n\014system_state\030\003 \001(\0132\027.sui.rpc" +
      ".v2.SystemStateH\002\210\001\001\022\035\n\020first_checkpoint" +
      "\030\004 \001(\004H\003\210\001\001\022\034\n\017last_checkpoint\030\005 \001(\004H\004\210\001" +
      "\001\022.\n\005start\030\006 \001(\0132\032.google.protobuf.Times" +
      "tampH\005\210\001\001\022,\n\003end\030\007 \001(\0132\032.google.protobuf" +
      ".TimestampH\006\210\001\001\022 \n\023reference_gas_price\030\010" +
      " \001(\004H\007\210\001\001\0228\n\017protocol_config\030\t \001(\0132\032.sui" +
      ".rpc.v2.ProtocolConfigH\010\210\001\001B\010\n\006_epochB\014\n" +
      "\n_committeeB\017\n\r_system_stateB\023\n\021_first_c" +
      "heckpointB\022\n\020_last_checkpointB\010\n\006_startB" +
      "\006\n\004_endB\026\n\024_reference_gas_priceB\022\n\020_prot" +
      "ocol_configb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          sui.rpc.v2.ProtocolConfigOuterClass.getDescriptor(),
          sui.rpc.v2.Signature.getDescriptor(),
          sui.rpc.v2.SystemStateOuterClass.getDescriptor(),
        });
    internal_static_sui_rpc_v2_Epoch_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sui_rpc_v2_Epoch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sui_rpc_v2_Epoch_descriptor,
        new java.lang.String[] { "Epoch", "Committee", "SystemState", "FirstCheckpoint", "LastCheckpoint", "Start", "End", "ReferenceGasPrice", "ProtocolConfig", });
    com.google.protobuf.TimestampProto.getDescriptor();
    sui.rpc.v2.ProtocolConfigOuterClass.getDescriptor();
    sui.rpc.v2.Signature.getDescriptor();
    sui.rpc.v2.SystemStateOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
