// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sui/rpc/v2/error_reason.proto

// Protobuf Java Version: 3.25.3
package sui.rpc.v2;

public final class ErrorReasonOuterClass {
  private ErrorReasonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code sui.rpc.v2.ErrorReason}
   */
  public enum ErrorReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERROR_REASON_UNKNOWN = 0;</code>
     */
    ERROR_REASON_UNKNOWN(0),
    /**
     * <code>FIELD_INVALID = 1;</code>
     */
    FIELD_INVALID(1),
    /**
     * <code>FIELD_MISSING = 2;</code>
     */
    FIELD_MISSING(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ERROR_REASON_UNKNOWN = 0;</code>
     */
    public static final int ERROR_REASON_UNKNOWN_VALUE = 0;
    /**
     * <code>FIELD_INVALID = 1;</code>
     */
    public static final int FIELD_INVALID_VALUE = 1;
    /**
     * <code>FIELD_MISSING = 2;</code>
     */
    public static final int FIELD_MISSING_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorReason valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorReason forNumber(int value) {
      switch (value) {
        case 0: return ERROR_REASON_UNKNOWN;
        case 1: return FIELD_INVALID;
        case 2: return FIELD_MISSING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorReason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorReason>() {
            public ErrorReason findValueByNumber(int number) {
              return ErrorReason.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sui.rpc.v2.ErrorReasonOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorReason[] VALUES = values();

    public static ErrorReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorReason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:sui.rpc.v2.ErrorReason)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035sui/rpc/v2/error_reason.proto\022\nsui.rpc" +
      ".v2*M\n\013ErrorReason\022\030\n\024ERROR_REASON_UNKNO" +
      "WN\020\000\022\021\n\rFIELD_INVALID\020\001\022\021\n\rFIELD_MISSING" +
      "\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
