// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sui/rpc/v2/object_reference.proto

// Protobuf Java Version: 3.25.3
package sui.rpc.v2;

public final class ObjectReferenceOuterClass {
  private ObjectReferenceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ObjectReferenceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sui.rpc.v2.ObjectReference)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The object id of this object.
     * </pre>
     *
     * <code>optional string object_id = 1;</code>
     * @return Whether the objectId field is set.
     */
    boolean hasObjectId();
    /**
     * <pre>
     * The object id of this object.
     * </pre>
     *
     * <code>optional string object_id = 1;</code>
     * @return The objectId.
     */
    java.lang.String getObjectId();
    /**
     * <pre>
     * The object id of this object.
     * </pre>
     *
     * <code>optional string object_id = 1;</code>
     * @return The bytes for objectId.
     */
    com.google.protobuf.ByteString
        getObjectIdBytes();

    /**
     * <pre>
     * The version of this object.
     * </pre>
     *
     * <code>optional uint64 version = 2;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <pre>
     * The version of this object.
     * </pre>
     *
     * <code>optional uint64 version = 2;</code>
     * @return The version.
     */
    long getVersion();

    /**
     * <pre>
     * The digest of this object.
     * </pre>
     *
     * <code>optional string digest = 3;</code>
     * @return Whether the digest field is set.
     */
    boolean hasDigest();
    /**
     * <pre>
     * The digest of this object.
     * </pre>
     *
     * <code>optional string digest = 3;</code>
     * @return The digest.
     */
    java.lang.String getDigest();
    /**
     * <pre>
     * The digest of this object.
     * </pre>
     *
     * <code>optional string digest = 3;</code>
     * @return The bytes for digest.
     */
    com.google.protobuf.ByteString
        getDigestBytes();
  }
  /**
   * <pre>
   * Reference to an object.
   * </pre>
   *
   * Protobuf type {@code sui.rpc.v2.ObjectReference}
   */
  public static final class ObjectReference extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sui.rpc.v2.ObjectReference)
      ObjectReferenceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ObjectReference.newBuilder() to construct.
    private ObjectReference(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ObjectReference() {
      objectId_ = "";
      digest_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ObjectReference();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sui.rpc.v2.ObjectReferenceOuterClass.internal_static_sui_rpc_v2_ObjectReference_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sui.rpc.v2.ObjectReferenceOuterClass.internal_static_sui_rpc_v2_ObjectReference_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference.class, sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference.Builder.class);
    }

    private int bitField0_;
    public static final int OBJECT_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object objectId_ = "";
    /**
     * <pre>
     * The object id of this object.
     * </pre>
     *
     * <code>optional string object_id = 1;</code>
     * @return Whether the objectId field is set.
     */
    @java.lang.Override
    public boolean hasObjectId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The object id of this object.
     * </pre>
     *
     * <code>optional string object_id = 1;</code>
     * @return The objectId.
     */
    @java.lang.Override
    public java.lang.String getObjectId() {
      java.lang.Object ref = objectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The object id of this object.
     * </pre>
     *
     * <code>optional string object_id = 1;</code>
     * @return The bytes for objectId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getObjectIdBytes() {
      java.lang.Object ref = objectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private long version_ = 0L;
    /**
     * <pre>
     * The version of this object.
     * </pre>
     *
     * <code>optional uint64 version = 2;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The version of this object.
     * </pre>
     *
     * <code>optional uint64 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }

    public static final int DIGEST_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object digest_ = "";
    /**
     * <pre>
     * The digest of this object.
     * </pre>
     *
     * <code>optional string digest = 3;</code>
     * @return Whether the digest field is set.
     */
    @java.lang.Override
    public boolean hasDigest() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The digest of this object.
     * </pre>
     *
     * <code>optional string digest = 3;</code>
     * @return The digest.
     */
    @java.lang.Override
    public java.lang.String getDigest() {
      java.lang.Object ref = digest_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        digest_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The digest of this object.
     * </pre>
     *
     * <code>optional string digest = 3;</code>
     * @return The bytes for digest.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDigestBytes() {
      java.lang.Object ref = digest_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        digest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt64(2, version_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, digest_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, version_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, digest_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference)) {
        return super.equals(obj);
      }
      sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference other = (sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference) obj;

      if (hasObjectId() != other.hasObjectId()) return false;
      if (hasObjectId()) {
        if (!getObjectId()
            .equals(other.getObjectId())) return false;
      }
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasDigest() != other.hasDigest()) return false;
      if (hasDigest()) {
        if (!getDigest()
            .equals(other.getDigest())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasObjectId()) {
        hash = (37 * hash) + OBJECT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getObjectId().hashCode();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getVersion());
      }
      if (hasDigest()) {
        hash = (37 * hash) + DIGEST_FIELD_NUMBER;
        hash = (53 * hash) + getDigest().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Reference to an object.
     * </pre>
     *
     * Protobuf type {@code sui.rpc.v2.ObjectReference}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sui.rpc.v2.ObjectReference)
        sui.rpc.v2.ObjectReferenceOuterClass.ObjectReferenceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sui.rpc.v2.ObjectReferenceOuterClass.internal_static_sui_rpc_v2_ObjectReference_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sui.rpc.v2.ObjectReferenceOuterClass.internal_static_sui_rpc_v2_ObjectReference_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference.class, sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference.Builder.class);
      }

      // Construct using sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        objectId_ = "";
        version_ = 0L;
        digest_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sui.rpc.v2.ObjectReferenceOuterClass.internal_static_sui_rpc_v2_ObjectReference_descriptor;
      }

      @java.lang.Override
      public sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference getDefaultInstanceForType() {
        return sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference.getDefaultInstance();
      }

      @java.lang.Override
      public sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference build() {
        sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference buildPartial() {
        sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference result = new sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.objectId_ = objectId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.digest_ = digest_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference) {
          return mergeFrom((sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference other) {
        if (other == sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference.getDefaultInstance()) return this;
        if (other.hasObjectId()) {
          objectId_ = other.objectId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasDigest()) {
          digest_ = other.digest_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                objectId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                version_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                digest_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object objectId_ = "";
      /**
       * <pre>
       * The object id of this object.
       * </pre>
       *
       * <code>optional string object_id = 1;</code>
       * @return Whether the objectId field is set.
       */
      public boolean hasObjectId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * The object id of this object.
       * </pre>
       *
       * <code>optional string object_id = 1;</code>
       * @return The objectId.
       */
      public java.lang.String getObjectId() {
        java.lang.Object ref = objectId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          objectId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The object id of this object.
       * </pre>
       *
       * <code>optional string object_id = 1;</code>
       * @return The bytes for objectId.
       */
      public com.google.protobuf.ByteString
          getObjectIdBytes() {
        java.lang.Object ref = objectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The object id of this object.
       * </pre>
       *
       * <code>optional string object_id = 1;</code>
       * @param value The objectId to set.
       * @return This builder for chaining.
       */
      public Builder setObjectId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        objectId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The object id of this object.
       * </pre>
       *
       * <code>optional string object_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearObjectId() {
        objectId_ = getDefaultInstance().getObjectId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The object id of this object.
       * </pre>
       *
       * <code>optional string object_id = 1;</code>
       * @param value The bytes for objectId to set.
       * @return This builder for chaining.
       */
      public Builder setObjectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        objectId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long version_ ;
      /**
       * <pre>
       * The version of this object.
       * </pre>
       *
       * <code>optional uint64 version = 2;</code>
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The version of this object.
       * </pre>
       *
       * <code>optional uint64 version = 2;</code>
       * @return The version.
       */
      @java.lang.Override
      public long getVersion() {
        return version_;
      }
      /**
       * <pre>
       * The version of this object.
       * </pre>
       *
       * <code>optional uint64 version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {

        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The version of this object.
       * </pre>
       *
       * <code>optional uint64 version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object digest_ = "";
      /**
       * <pre>
       * The digest of this object.
       * </pre>
       *
       * <code>optional string digest = 3;</code>
       * @return Whether the digest field is set.
       */
      public boolean hasDigest() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * The digest of this object.
       * </pre>
       *
       * <code>optional string digest = 3;</code>
       * @return The digest.
       */
      public java.lang.String getDigest() {
        java.lang.Object ref = digest_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          digest_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The digest of this object.
       * </pre>
       *
       * <code>optional string digest = 3;</code>
       * @return The bytes for digest.
       */
      public com.google.protobuf.ByteString
          getDigestBytes() {
        java.lang.Object ref = digest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          digest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The digest of this object.
       * </pre>
       *
       * <code>optional string digest = 3;</code>
       * @param value The digest to set.
       * @return This builder for chaining.
       */
      public Builder setDigest(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        digest_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The digest of this object.
       * </pre>
       *
       * <code>optional string digest = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDigest() {
        digest_ = getDefaultInstance().getDigest();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The digest of this object.
       * </pre>
       *
       * <code>optional string digest = 3;</code>
       * @param value The bytes for digest to set.
       * @return This builder for chaining.
       */
      public Builder setDigestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        digest_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sui.rpc.v2.ObjectReference)
    }

    // @@protoc_insertion_point(class_scope:sui.rpc.v2.ObjectReference)
    private static final sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference();
    }

    public static sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ObjectReference>
        PARSER = new com.google.protobuf.AbstractParser<ObjectReference>() {
      @java.lang.Override
      public ObjectReference parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ObjectReference> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ObjectReference> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sui.rpc.v2.ObjectReferenceOuterClass.ObjectReference getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sui_rpc_v2_ObjectReference_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sui_rpc_v2_ObjectReference_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!sui/rpc/v2/object_reference.proto\022\nsui" +
      ".rpc.v2\"y\n\017ObjectReference\022\026\n\tobject_id\030" +
      "\001 \001(\tH\000\210\001\001\022\024\n\007version\030\002 \001(\004H\001\210\001\001\022\023\n\006dige" +
      "st\030\003 \001(\tH\002\210\001\001B\014\n\n_object_idB\n\n\010_versionB" +
      "\t\n\007_digestb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sui_rpc_v2_ObjectReference_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sui_rpc_v2_ObjectReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sui_rpc_v2_ObjectReference_descriptor,
        new java.lang.String[] { "ObjectId", "Version", "Digest", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
