// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sui/rpc/v2/owner.proto

// Protobuf Java Version: 3.25.3
package sui.rpc.v2;

public final class OwnerOuterClass {
  private OwnerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OwnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sui.rpc.v2.Owner)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
     * @return Whether the kind field is set.
     */
    boolean hasKind();
    /**
     * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
     * @return The enum numeric value on the wire for kind.
     */
    int getKindValue();
    /**
     * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
     * @return The kind.
     */
    sui.rpc.v2.OwnerOuterClass.Owner.OwnerKind getKind();

    /**
     * <pre>
     * Address or ObjectId of the owner
     * </pre>
     *
     * <code>optional string address = 2;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <pre>
     * Address or ObjectId of the owner
     * </pre>
     *
     * <code>optional string address = 2;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <pre>
     * Address or ObjectId of the owner
     * </pre>
     *
     * <code>optional string address = 2;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * The `initial_shared_version` if kind is `SHARED` or `start_version` if kind `CONSENSUS_ADDRESS`.
     * </pre>
     *
     * <code>optional uint64 version = 3;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <pre>
     * The `initial_shared_version` if kind is `SHARED` or `start_version` if kind `CONSENSUS_ADDRESS`.
     * </pre>
     *
     * <code>optional uint64 version = 3;</code>
     * @return The version.
     */
    long getVersion();
  }
  /**
   * <pre>
   * Enum of different types of ownership for an object.
   * </pre>
   *
   * Protobuf type {@code sui.rpc.v2.Owner}
   */
  public static final class Owner extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sui.rpc.v2.Owner)
      OwnerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Owner.newBuilder() to construct.
    private Owner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Owner() {
      kind_ = 0;
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Owner();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sui.rpc.v2.OwnerOuterClass.internal_static_sui_rpc_v2_Owner_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sui.rpc.v2.OwnerOuterClass.internal_static_sui_rpc_v2_Owner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sui.rpc.v2.OwnerOuterClass.Owner.class, sui.rpc.v2.OwnerOuterClass.Owner.Builder.class);
    }

    /**
     * Protobuf enum {@code sui.rpc.v2.Owner.OwnerKind}
     */
    public enum OwnerKind
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OWNER_KIND_UNKNOWN = 0;</code>
       */
      OWNER_KIND_UNKNOWN(0),
      /**
       * <code>ADDRESS = 1;</code>
       */
      ADDRESS(1),
      /**
       * <code>OBJECT = 2;</code>
       */
      OBJECT(2),
      /**
       * <code>SHARED = 3;</code>
       */
      SHARED(3),
      /**
       * <code>IMMUTABLE = 4;</code>
       */
      IMMUTABLE(4),
      /**
       * <code>CONSENSUS_ADDRESS = 5;</code>
       */
      CONSENSUS_ADDRESS(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>OWNER_KIND_UNKNOWN = 0;</code>
       */
      public static final int OWNER_KIND_UNKNOWN_VALUE = 0;
      /**
       * <code>ADDRESS = 1;</code>
       */
      public static final int ADDRESS_VALUE = 1;
      /**
       * <code>OBJECT = 2;</code>
       */
      public static final int OBJECT_VALUE = 2;
      /**
       * <code>SHARED = 3;</code>
       */
      public static final int SHARED_VALUE = 3;
      /**
       * <code>IMMUTABLE = 4;</code>
       */
      public static final int IMMUTABLE_VALUE = 4;
      /**
       * <code>CONSENSUS_ADDRESS = 5;</code>
       */
      public static final int CONSENSUS_ADDRESS_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static OwnerKind valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static OwnerKind forNumber(int value) {
        switch (value) {
          case 0: return OWNER_KIND_UNKNOWN;
          case 1: return ADDRESS;
          case 2: return OBJECT;
          case 3: return SHARED;
          case 4: return IMMUTABLE;
          case 5: return CONSENSUS_ADDRESS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OwnerKind>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          OwnerKind> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OwnerKind>() {
              public OwnerKind findValueByNumber(int number) {
                return OwnerKind.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sui.rpc.v2.OwnerOuterClass.Owner.getDescriptor().getEnumTypes().get(0);
      }

      private static final OwnerKind[] VALUES = values();

      public static OwnerKind valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private OwnerKind(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sui.rpc.v2.Owner.OwnerKind)
    }

    private int bitField0_;
    public static final int KIND_FIELD_NUMBER = 1;
    private int kind_ = 0;
    /**
     * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
     * @return Whether the kind field is set.
     */
    @java.lang.Override public boolean hasKind() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override public int getKindValue() {
      return kind_;
    }
    /**
     * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
     * @return The kind.
     */
    @java.lang.Override public sui.rpc.v2.OwnerOuterClass.Owner.OwnerKind getKind() {
      sui.rpc.v2.OwnerOuterClass.Owner.OwnerKind result = sui.rpc.v2.OwnerOuterClass.Owner.OwnerKind.forNumber(kind_);
      return result == null ? sui.rpc.v2.OwnerOuterClass.Owner.OwnerKind.UNRECOGNIZED : result;
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <pre>
     * Address or ObjectId of the owner
     * </pre>
     *
     * <code>optional string address = 2;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Address or ObjectId of the owner
     * </pre>
     *
     * <code>optional string address = 2;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Address or ObjectId of the owner
     * </pre>
     *
     * <code>optional string address = 2;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private long version_ = 0L;
    /**
     * <pre>
     * The `initial_shared_version` if kind is `SHARED` or `start_version` if kind `CONSENSUS_ADDRESS`.
     * </pre>
     *
     * <code>optional uint64 version = 3;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The `initial_shared_version` if kind is `SHARED` or `start_version` if kind `CONSENSUS_ADDRESS`.
     * </pre>
     *
     * <code>optional uint64 version = 3;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, kind_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(3, version_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, kind_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, version_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sui.rpc.v2.OwnerOuterClass.Owner)) {
        return super.equals(obj);
      }
      sui.rpc.v2.OwnerOuterClass.Owner other = (sui.rpc.v2.OwnerOuterClass.Owner) obj;

      if (hasKind() != other.hasKind()) return false;
      if (hasKind()) {
        if (kind_ != other.kind_) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasKind()) {
        hash = (37 * hash) + KIND_FIELD_NUMBER;
        hash = (53 * hash) + kind_;
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getVersion());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sui.rpc.v2.OwnerOuterClass.Owner parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.OwnerOuterClass.Owner parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.OwnerOuterClass.Owner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.OwnerOuterClass.Owner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.OwnerOuterClass.Owner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.OwnerOuterClass.Owner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.OwnerOuterClass.Owner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.OwnerOuterClass.Owner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sui.rpc.v2.OwnerOuterClass.Owner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sui.rpc.v2.OwnerOuterClass.Owner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sui.rpc.v2.OwnerOuterClass.Owner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.OwnerOuterClass.Owner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sui.rpc.v2.OwnerOuterClass.Owner prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Enum of different types of ownership for an object.
     * </pre>
     *
     * Protobuf type {@code sui.rpc.v2.Owner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sui.rpc.v2.Owner)
        sui.rpc.v2.OwnerOuterClass.OwnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sui.rpc.v2.OwnerOuterClass.internal_static_sui_rpc_v2_Owner_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sui.rpc.v2.OwnerOuterClass.internal_static_sui_rpc_v2_Owner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sui.rpc.v2.OwnerOuterClass.Owner.class, sui.rpc.v2.OwnerOuterClass.Owner.Builder.class);
      }

      // Construct using sui.rpc.v2.OwnerOuterClass.Owner.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        kind_ = 0;
        address_ = "";
        version_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sui.rpc.v2.OwnerOuterClass.internal_static_sui_rpc_v2_Owner_descriptor;
      }

      @java.lang.Override
      public sui.rpc.v2.OwnerOuterClass.Owner getDefaultInstanceForType() {
        return sui.rpc.v2.OwnerOuterClass.Owner.getDefaultInstance();
      }

      @java.lang.Override
      public sui.rpc.v2.OwnerOuterClass.Owner build() {
        sui.rpc.v2.OwnerOuterClass.Owner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sui.rpc.v2.OwnerOuterClass.Owner buildPartial() {
        sui.rpc.v2.OwnerOuterClass.Owner result = new sui.rpc.v2.OwnerOuterClass.Owner(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sui.rpc.v2.OwnerOuterClass.Owner result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.kind_ = kind_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.address_ = address_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sui.rpc.v2.OwnerOuterClass.Owner) {
          return mergeFrom((sui.rpc.v2.OwnerOuterClass.Owner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sui.rpc.v2.OwnerOuterClass.Owner other) {
        if (other == sui.rpc.v2.OwnerOuterClass.Owner.getDefaultInstance()) return this;
        if (other.hasKind()) {
          setKind(other.getKind());
        }
        if (other.hasAddress()) {
          address_ = other.address_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                kind_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                version_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int kind_ = 0;
      /**
       * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
       * @return Whether the kind field is set.
       */
      @java.lang.Override public boolean hasKind() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
       * @return The enum numeric value on the wire for kind.
       */
      @java.lang.Override public int getKindValue() {
        return kind_;
      }
      /**
       * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
       * @param value The enum numeric value on the wire for kind to set.
       * @return This builder for chaining.
       */
      public Builder setKindValue(int value) {
        kind_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
       * @return The kind.
       */
      @java.lang.Override
      public sui.rpc.v2.OwnerOuterClass.Owner.OwnerKind getKind() {
        sui.rpc.v2.OwnerOuterClass.Owner.OwnerKind result = sui.rpc.v2.OwnerOuterClass.Owner.OwnerKind.forNumber(kind_);
        return result == null ? sui.rpc.v2.OwnerOuterClass.Owner.OwnerKind.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
       * @param value The kind to set.
       * @return This builder for chaining.
       */
      public Builder setKind(sui.rpc.v2.OwnerOuterClass.Owner.OwnerKind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        kind_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .sui.rpc.v2.Owner.OwnerKind kind = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000001);
        kind_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       * Address or ObjectId of the owner
       * </pre>
       *
       * <code>optional string address = 2;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Address or ObjectId of the owner
       * </pre>
       *
       * <code>optional string address = 2;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Address or ObjectId of the owner
       * </pre>
       *
       * <code>optional string address = 2;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Address or ObjectId of the owner
       * </pre>
       *
       * <code>optional string address = 2;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Address or ObjectId of the owner
       * </pre>
       *
       * <code>optional string address = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Address or ObjectId of the owner
       * </pre>
       *
       * <code>optional string address = 2;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long version_ ;
      /**
       * <pre>
       * The `initial_shared_version` if kind is `SHARED` or `start_version` if kind `CONSENSUS_ADDRESS`.
       * </pre>
       *
       * <code>optional uint64 version = 3;</code>
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * The `initial_shared_version` if kind is `SHARED` or `start_version` if kind `CONSENSUS_ADDRESS`.
       * </pre>
       *
       * <code>optional uint64 version = 3;</code>
       * @return The version.
       */
      @java.lang.Override
      public long getVersion() {
        return version_;
      }
      /**
       * <pre>
       * The `initial_shared_version` if kind is `SHARED` or `start_version` if kind `CONSENSUS_ADDRESS`.
       * </pre>
       *
       * <code>optional uint64 version = 3;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {

        version_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The `initial_shared_version` if kind is `SHARED` or `start_version` if kind `CONSENSUS_ADDRESS`.
       * </pre>
       *
       * <code>optional uint64 version = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sui.rpc.v2.Owner)
    }

    // @@protoc_insertion_point(class_scope:sui.rpc.v2.Owner)
    private static final sui.rpc.v2.OwnerOuterClass.Owner DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sui.rpc.v2.OwnerOuterClass.Owner();
    }

    public static sui.rpc.v2.OwnerOuterClass.Owner getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Owner>
        PARSER = new com.google.protobuf.AbstractParser<Owner>() {
      @java.lang.Override
      public Owner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Owner> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Owner> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sui.rpc.v2.OwnerOuterClass.Owner getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sui_rpc_v2_Owner_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sui_rpc_v2_Owner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026sui/rpc/v2/owner.proto\022\nsui.rpc.v2\"\364\001\n" +
      "\005Owner\022.\n\004kind\030\001 \001(\0162\033.sui.rpc.v2.Owner." +
      "OwnerKindH\000\210\001\001\022\024\n\007address\030\002 \001(\tH\001\210\001\001\022\024\n\007" +
      "version\030\003 \001(\004H\002\210\001\001\"n\n\tOwnerKind\022\026\n\022OWNER" +
      "_KIND_UNKNOWN\020\000\022\013\n\007ADDRESS\020\001\022\n\n\006OBJECT\020\002" +
      "\022\n\n\006SHARED\020\003\022\r\n\tIMMUTABLE\020\004\022\025\n\021CONSENSUS" +
      "_ADDRESS\020\005B\007\n\005_kindB\n\n\010_addressB\n\n\010_vers" +
      "ionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sui_rpc_v2_Owner_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sui_rpc_v2_Owner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sui_rpc_v2_Owner_descriptor,
        new java.lang.String[] { "Kind", "Address", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
