// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sui/rpc/v2/protocol_config.proto

// Protobuf Java Version: 3.25.3
package sui.rpc.v2;

public final class ProtocolConfigOuterClass {
  private ProtocolConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocolConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sui.rpc.v2.ProtocolConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 protocol_version = 1;</code>
     * @return Whether the protocolVersion field is set.
     */
    boolean hasProtocolVersion();
    /**
     * <code>optional uint64 protocol_version = 1;</code>
     * @return The protocolVersion.
     */
    long getProtocolVersion();

    /**
     * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
     */
    int getFeatureFlagsCount();
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
     */
    boolean containsFeatureFlags(
        java.lang.String key);
    /**
     * Use {@link #getFeatureFlagsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Boolean>
    getFeatureFlags();
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.Boolean>
    getFeatureFlagsMap();
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
     */
    boolean getFeatureFlagsOrDefault(
        java.lang.String key,
        boolean defaultValue);
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
     */
    boolean getFeatureFlagsOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, string&gt; attributes = 3;</code>
     */
    int getAttributesCount();
    /**
     * <code>map&lt;string, string&gt; attributes = 3;</code>
     */
    boolean containsAttributes(
        java.lang.String key);
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAttributes();
    /**
     * <code>map&lt;string, string&gt; attributes = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAttributesMap();
    /**
     * <code>map&lt;string, string&gt; attributes = 3;</code>
     */
    /* nullable */
java.lang.String getAttributesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; attributes = 3;</code>
     */
    java.lang.String getAttributesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code sui.rpc.v2.ProtocolConfig}
   */
  public static final class ProtocolConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sui.rpc.v2.ProtocolConfig)
      ProtocolConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtocolConfig.newBuilder() to construct.
    private ProtocolConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtocolConfig() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtocolConfig();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sui.rpc.v2.ProtocolConfigOuterClass.internal_static_sui_rpc_v2_ProtocolConfig_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetFeatureFlags();
        case 3:
          return internalGetAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sui.rpc.v2.ProtocolConfigOuterClass.internal_static_sui_rpc_v2_ProtocolConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.class, sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.Builder.class);
    }

    private int bitField0_;
    public static final int PROTOCOL_VERSION_FIELD_NUMBER = 1;
    private long protocolVersion_ = 0L;
    /**
     * <code>optional uint64 protocol_version = 1;</code>
     * @return Whether the protocolVersion field is set.
     */
    @java.lang.Override
    public boolean hasProtocolVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 protocol_version = 1;</code>
     * @return The protocolVersion.
     */
    @java.lang.Override
    public long getProtocolVersion() {
      return protocolVersion_;
    }

    public static final int FEATURE_FLAGS_FIELD_NUMBER = 2;
    private static final class FeatureFlagsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Boolean> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Boolean>newDefaultInstance(
                  sui.rpc.v2.ProtocolConfigOuterClass.internal_static_sui_rpc_v2_ProtocolConfig_FeatureFlagsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.BOOL,
                  false);
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Boolean> featureFlags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
    internalGetFeatureFlags() {
      if (featureFlags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FeatureFlagsDefaultEntryHolder.defaultEntry);
      }
      return featureFlags_;
    }
    public int getFeatureFlagsCount() {
      return internalGetFeatureFlags().getMap().size();
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
     */
    @java.lang.Override
    public boolean containsFeatureFlags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetFeatureFlags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFeatureFlagsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Boolean> getFeatureFlags() {
      return getFeatureFlagsMap();
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Boolean> getFeatureFlagsMap() {
      return internalGetFeatureFlags().getMap();
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
     */
    @java.lang.Override
    public boolean getFeatureFlagsOrDefault(
        java.lang.String key,
        boolean defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetFeatureFlags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
     */
    @java.lang.Override
    public boolean getFeatureFlagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetFeatureFlags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 3;
    private static final class AttributesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  sui.rpc.v2.ProtocolConfigOuterClass.internal_static_sui_rpc_v2_ProtocolConfig_AttributesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attributes_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }
    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 3;</code>
     */
    @java.lang.Override
    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getAttributesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, protocolVersion_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetFeatureFlags(),
          FeatureFlagsDefaultEntryHolder.defaultEntry,
          2);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttributes(),
          AttributesDefaultEntryHolder.defaultEntry,
          3);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, protocolVersion_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Boolean> entry
           : internalGetFeatureFlags().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
        featureFlags__ = FeatureFlagsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, featureFlags__);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAttributes().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, attributes__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig)) {
        return super.equals(obj);
      }
      sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig other = (sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig) obj;

      if (hasProtocolVersion() != other.hasProtocolVersion()) return false;
      if (hasProtocolVersion()) {
        if (getProtocolVersion()
            != other.getProtocolVersion()) return false;
      }
      if (!internalGetFeatureFlags().equals(
          other.internalGetFeatureFlags())) return false;
      if (!internalGetAttributes().equals(
          other.internalGetAttributes())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProtocolVersion()) {
        hash = (37 * hash) + PROTOCOL_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getProtocolVersion());
      }
      if (!internalGetFeatureFlags().getMap().isEmpty()) {
        hash = (37 * hash) + FEATURE_FLAGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetFeatureFlags().hashCode();
      }
      if (!internalGetAttributes().getMap().isEmpty()) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttributes().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sui.rpc.v2.ProtocolConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sui.rpc.v2.ProtocolConfig)
        sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sui.rpc.v2.ProtocolConfigOuterClass.internal_static_sui_rpc_v2_ProtocolConfig_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetFeatureFlags();
          case 3:
            return internalGetAttributes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableFeatureFlags();
          case 3:
            return internalGetMutableAttributes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sui.rpc.v2.ProtocolConfigOuterClass.internal_static_sui_rpc_v2_ProtocolConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.class, sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.Builder.class);
      }

      // Construct using sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        protocolVersion_ = 0L;
        internalGetMutableFeatureFlags().clear();
        internalGetMutableAttributes().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sui.rpc.v2.ProtocolConfigOuterClass.internal_static_sui_rpc_v2_ProtocolConfig_descriptor;
      }

      @java.lang.Override
      public sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig getDefaultInstanceForType() {
        return sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.getDefaultInstance();
      }

      @java.lang.Override
      public sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig build() {
        sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig buildPartial() {
        sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig result = new sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.protocolVersion_ = protocolVersion_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.featureFlags_ = internalGetFeatureFlags();
          result.featureFlags_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.attributes_ = internalGetAttributes();
          result.attributes_.makeImmutable();
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig) {
          return mergeFrom((sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig other) {
        if (other == sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig.getDefaultInstance()) return this;
        if (other.hasProtocolVersion()) {
          setProtocolVersion(other.getProtocolVersion());
        }
        internalGetMutableFeatureFlags().mergeFrom(
            other.internalGetFeatureFlags());
        bitField0_ |= 0x00000002;
        internalGetMutableAttributes().mergeFrom(
            other.internalGetAttributes());
        bitField0_ |= 0x00000004;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                protocolVersion_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
                featureFlags__ = input.readMessage(
                    FeatureFlagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableFeatureFlags().getMutableMap().put(
                    featureFlags__.getKey(), featureFlags__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                attributes__ = input.readMessage(
                    AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableAttributes().getMutableMap().put(
                    attributes__.getKey(), attributes__.getValue());
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long protocolVersion_ ;
      /**
       * <code>optional uint64 protocol_version = 1;</code>
       * @return Whether the protocolVersion field is set.
       */
      @java.lang.Override
      public boolean hasProtocolVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 protocol_version = 1;</code>
       * @return The protocolVersion.
       */
      @java.lang.Override
      public long getProtocolVersion() {
        return protocolVersion_;
      }
      /**
       * <code>optional uint64 protocol_version = 1;</code>
       * @param value The protocolVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolVersion(long value) {

        protocolVersion_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 protocol_version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocolVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protocolVersion_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Boolean> featureFlags_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
          internalGetFeatureFlags() {
        if (featureFlags_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FeatureFlagsDefaultEntryHolder.defaultEntry);
        }
        return featureFlags_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
          internalGetMutableFeatureFlags() {
        if (featureFlags_ == null) {
          featureFlags_ = com.google.protobuf.MapField.newMapField(
              FeatureFlagsDefaultEntryHolder.defaultEntry);
        }
        if (!featureFlags_.isMutable()) {
          featureFlags_ = featureFlags_.copy();
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return featureFlags_;
      }
      public int getFeatureFlagsCount() {
        return internalGetFeatureFlags().getMap().size();
      }
      /**
       * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
       */
      @java.lang.Override
      public boolean containsFeatureFlags(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetFeatureFlags().getMap().containsKey(key);
      }
      /**
       * Use {@link #getFeatureFlagsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Boolean> getFeatureFlags() {
        return getFeatureFlagsMap();
      }
      /**
       * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.Boolean> getFeatureFlagsMap() {
        return internalGetFeatureFlags().getMap();
      }
      /**
       * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
       */
      @java.lang.Override
      public boolean getFeatureFlagsOrDefault(
          java.lang.String key,
          boolean defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Boolean> map =
            internalGetFeatureFlags().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
       */
      @java.lang.Override
      public boolean getFeatureFlagsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Boolean> map =
            internalGetFeatureFlags().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearFeatureFlags() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableFeatureFlags().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
       */
      public Builder removeFeatureFlags(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableFeatureFlags().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Boolean>
          getMutableFeatureFlags() {
        bitField0_ |= 0x00000002;
        return internalGetMutableFeatureFlags().getMutableMap();
      }
      /**
       * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
       */
      public Builder putFeatureFlags(
          java.lang.String key,
          boolean value) {
        if (key == null) { throw new NullPointerException("map key"); }

        internalGetMutableFeatureFlags().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, bool&gt; feature_flags = 2;</code>
       */
      public Builder putAllFeatureFlags(
          java.util.Map<java.lang.String, java.lang.Boolean> values) {
        internalGetMutableFeatureFlags().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> attributes_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetAttributes() {
        if (attributes_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttributesDefaultEntryHolder.defaultEntry);
        }
        return attributes_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableAttributes() {
        if (attributes_ == null) {
          attributes_ = com.google.protobuf.MapField.newMapField(
              AttributesDefaultEntryHolder.defaultEntry);
        }
        if (!attributes_.isMutable()) {
          attributes_ = attributes_.copy();
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return attributes_;
      }
      public int getAttributesCount() {
        return internalGetAttributes().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 3;</code>
       */
      @java.lang.Override
      public boolean containsAttributes(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetAttributes().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttributesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
        return getAttributesMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 3;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
        return internalGetAttributes().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 3;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getAttributesOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttributes().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 3;</code>
       */
      @java.lang.Override
      public java.lang.String getAttributesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttributes().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearAttributes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableAttributes().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 3;</code>
       */
      public Builder removeAttributes(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableAttributes().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableAttributes() {
        bitField0_ |= 0x00000004;
        return internalGetMutableAttributes().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 3;</code>
       */
      public Builder putAttributes(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableAttributes().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 3;</code>
       */
      public Builder putAllAttributes(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAttributes().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sui.rpc.v2.ProtocolConfig)
    }

    // @@protoc_insertion_point(class_scope:sui.rpc.v2.ProtocolConfig)
    private static final sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig();
    }

    public static sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtocolConfig>
        PARSER = new com.google.protobuf.AbstractParser<ProtocolConfig>() {
      @java.lang.Override
      public ProtocolConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProtocolConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtocolConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sui.rpc.v2.ProtocolConfigOuterClass.ProtocolConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sui_rpc_v2_ProtocolConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sui_rpc_v2_ProtocolConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sui_rpc_v2_ProtocolConfig_FeatureFlagsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sui_rpc_v2_ProtocolConfig_FeatureFlagsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sui_rpc_v2_ProtocolConfig_AttributesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sui_rpc_v2_ProtocolConfig_AttributesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n sui/rpc/v2/protocol_config.proto\022\nsui." +
      "rpc.v2\"\261\002\n\016ProtocolConfig\022\035\n\020protocol_ve" +
      "rsion\030\001 \001(\004H\000\210\001\001\022C\n\rfeature_flags\030\002 \003(\0132" +
      ",.sui.rpc.v2.ProtocolConfig.FeatureFlags" +
      "Entry\022>\n\nattributes\030\003 \003(\0132*.sui.rpc.v2.P" +
      "rotocolConfig.AttributesEntry\0323\n\021Feature" +
      "FlagsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\010:\002" +
      "8\001\0321\n\017AttributesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001B\023\n\021_protocol_versionb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sui_rpc_v2_ProtocolConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sui_rpc_v2_ProtocolConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sui_rpc_v2_ProtocolConfig_descriptor,
        new java.lang.String[] { "ProtocolVersion", "FeatureFlags", "Attributes", });
    internal_static_sui_rpc_v2_ProtocolConfig_FeatureFlagsEntry_descriptor =
      internal_static_sui_rpc_v2_ProtocolConfig_descriptor.getNestedTypes().get(0);
    internal_static_sui_rpc_v2_ProtocolConfig_FeatureFlagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sui_rpc_v2_ProtocolConfig_FeatureFlagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_sui_rpc_v2_ProtocolConfig_AttributesEntry_descriptor =
      internal_static_sui_rpc_v2_ProtocolConfig_descriptor.getNestedTypes().get(1);
    internal_static_sui_rpc_v2_ProtocolConfig_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sui_rpc_v2_ProtocolConfig_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
