// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sui/rpc/v2/signature_verification_service.proto

// Protobuf Java Version: 3.25.3
package sui.rpc.v2;

public final class SignatureVerificationServiceOuterClass {
  private SignatureVerificationServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VerifySignatureRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sui.rpc.v2.VerifySignatureRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The message to verify against.
     *
     * Today the only supported message types are `PersonalMessage` and
     * `TransactionData` and the `Bcs.name` must be set to indicate which type of
     * message is being verified.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <pre>
     * The message to verify against.
     *
     * Today the only supported message types are `PersonalMessage` and
     * `TransactionData` and the `Bcs.name` must be set to indicate which type of
     * message is being verified.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
     * @return The message.
     */
    sui.rpc.v2.BcsOuterClass.Bcs getMessage();
    /**
     * <pre>
     * The message to verify against.
     *
     * Today the only supported message types are `PersonalMessage` and
     * `TransactionData` and the `Bcs.name` must be set to indicate which type of
     * message is being verified.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
     */
    sui.rpc.v2.BcsOuterClass.BcsOrBuilder getMessageOrBuilder();

    /**
     * <pre>
     * The signature to verify.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
     * @return Whether the signature field is set.
     */
    boolean hasSignature();
    /**
     * <pre>
     * The signature to verify.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
     * @return The signature.
     */
    sui.rpc.v2.Signature.UserSignature getSignature();
    /**
     * <pre>
     * The signature to verify.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
     */
    sui.rpc.v2.Signature.UserSignatureOrBuilder getSignatureOrBuilder();

    /**
     * <pre>
     * Optional. Address to validate against the provided signature.
     *
     * If provided, this address will be compared against the the address derived
     * from the provide signature and a successful response will only be returned
     * if they match.
     * </pre>
     *
     * <code>optional string address = 3;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <pre>
     * Optional. Address to validate against the provided signature.
     *
     * If provided, this address will be compared against the the address derived
     * from the provide signature and a successful response will only be returned
     * if they match.
     * </pre>
     *
     * <code>optional string address = 3;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <pre>
     * Optional. Address to validate against the provided signature.
     *
     * If provided, this address will be compared against the the address derived
     * from the provide signature and a successful response will only be returned
     * if they match.
     * </pre>
     *
     * <code>optional string address = 3;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * The set of JWKs to use when verifying Zklogin signatures.
     * If this is empty the current set of valid JWKs stored onchain will be used
     * </pre>
     *
     * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
     */
    java.util.List<sui.rpc.v2.TransactionOuterClass.ActiveJwk> 
        getJwksList();
    /**
     * <pre>
     * The set of JWKs to use when verifying Zklogin signatures.
     * If this is empty the current set of valid JWKs stored onchain will be used
     * </pre>
     *
     * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
     */
    sui.rpc.v2.TransactionOuterClass.ActiveJwk getJwks(int index);
    /**
     * <pre>
     * The set of JWKs to use when verifying Zklogin signatures.
     * If this is empty the current set of valid JWKs stored onchain will be used
     * </pre>
     *
     * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
     */
    int getJwksCount();
    /**
     * <pre>
     * The set of JWKs to use when verifying Zklogin signatures.
     * If this is empty the current set of valid JWKs stored onchain will be used
     * </pre>
     *
     * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
     */
    java.util.List<? extends sui.rpc.v2.TransactionOuterClass.ActiveJwkOrBuilder> 
        getJwksOrBuilderList();
    /**
     * <pre>
     * The set of JWKs to use when verifying Zklogin signatures.
     * If this is empty the current set of valid JWKs stored onchain will be used
     * </pre>
     *
     * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
     */
    sui.rpc.v2.TransactionOuterClass.ActiveJwkOrBuilder getJwksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code sui.rpc.v2.VerifySignatureRequest}
   */
  public static final class VerifySignatureRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sui.rpc.v2.VerifySignatureRequest)
      VerifySignatureRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VerifySignatureRequest.newBuilder() to construct.
    private VerifySignatureRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VerifySignatureRequest() {
      address_ = "";
      jwks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VerifySignatureRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sui.rpc.v2.SignatureVerificationServiceOuterClass.internal_static_sui_rpc_v2_VerifySignatureRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sui.rpc.v2.SignatureVerificationServiceOuterClass.internal_static_sui_rpc_v2_VerifySignatureRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest.class, sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private sui.rpc.v2.BcsOuterClass.Bcs message_;
    /**
     * <pre>
     * The message to verify against.
     *
     * Today the only supported message types are `PersonalMessage` and
     * `TransactionData` and the `Bcs.name` must be set to indicate which type of
     * message is being verified.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The message to verify against.
     *
     * Today the only supported message types are `PersonalMessage` and
     * `TransactionData` and the `Bcs.name` must be set to indicate which type of
     * message is being verified.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public sui.rpc.v2.BcsOuterClass.Bcs getMessage() {
      return message_ == null ? sui.rpc.v2.BcsOuterClass.Bcs.getDefaultInstance() : message_;
    }
    /**
     * <pre>
     * The message to verify against.
     *
     * Today the only supported message types are `PersonalMessage` and
     * `TransactionData` and the `Bcs.name` must be set to indicate which type of
     * message is being verified.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
     */
    @java.lang.Override
    public sui.rpc.v2.BcsOuterClass.BcsOrBuilder getMessageOrBuilder() {
      return message_ == null ? sui.rpc.v2.BcsOuterClass.Bcs.getDefaultInstance() : message_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private sui.rpc.v2.Signature.UserSignature signature_;
    /**
     * <pre>
     * The signature to verify.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
     * @return Whether the signature field is set.
     */
    @java.lang.Override
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The signature to verify.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
     * @return The signature.
     */
    @java.lang.Override
    public sui.rpc.v2.Signature.UserSignature getSignature() {
      return signature_ == null ? sui.rpc.v2.Signature.UserSignature.getDefaultInstance() : signature_;
    }
    /**
     * <pre>
     * The signature to verify.
     * </pre>
     *
     * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
     */
    @java.lang.Override
    public sui.rpc.v2.Signature.UserSignatureOrBuilder getSignatureOrBuilder() {
      return signature_ == null ? sui.rpc.v2.Signature.UserSignature.getDefaultInstance() : signature_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <pre>
     * Optional. Address to validate against the provided signature.
     *
     * If provided, this address will be compared against the the address derived
     * from the provide signature and a successful response will only be returned
     * if they match.
     * </pre>
     *
     * <code>optional string address = 3;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Optional. Address to validate against the provided signature.
     *
     * If provided, this address will be compared against the the address derived
     * from the provide signature and a successful response will only be returned
     * if they match.
     * </pre>
     *
     * <code>optional string address = 3;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional. Address to validate against the provided signature.
     *
     * If provided, this address will be compared against the the address derived
     * from the provide signature and a successful response will only be returned
     * if they match.
     * </pre>
     *
     * <code>optional string address = 3;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JWKS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<sui.rpc.v2.TransactionOuterClass.ActiveJwk> jwks_;
    /**
     * <pre>
     * The set of JWKs to use when verifying Zklogin signatures.
     * If this is empty the current set of valid JWKs stored onchain will be used
     * </pre>
     *
     * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
     */
    @java.lang.Override
    public java.util.List<sui.rpc.v2.TransactionOuterClass.ActiveJwk> getJwksList() {
      return jwks_;
    }
    /**
     * <pre>
     * The set of JWKs to use when verifying Zklogin signatures.
     * If this is empty the current set of valid JWKs stored onchain will be used
     * </pre>
     *
     * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends sui.rpc.v2.TransactionOuterClass.ActiveJwkOrBuilder> 
        getJwksOrBuilderList() {
      return jwks_;
    }
    /**
     * <pre>
     * The set of JWKs to use when verifying Zklogin signatures.
     * If this is empty the current set of valid JWKs stored onchain will be used
     * </pre>
     *
     * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
     */
    @java.lang.Override
    public int getJwksCount() {
      return jwks_.size();
    }
    /**
     * <pre>
     * The set of JWKs to use when verifying Zklogin signatures.
     * If this is empty the current set of valid JWKs stored onchain will be used
     * </pre>
     *
     * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
     */
    @java.lang.Override
    public sui.rpc.v2.TransactionOuterClass.ActiveJwk getJwks(int index) {
      return jwks_.get(index);
    }
    /**
     * <pre>
     * The set of JWKs to use when verifying Zklogin signatures.
     * If this is empty the current set of valid JWKs stored onchain will be used
     * </pre>
     *
     * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
     */
    @java.lang.Override
    public sui.rpc.v2.TransactionOuterClass.ActiveJwkOrBuilder getJwksOrBuilder(
        int index) {
      return jwks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getMessage());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getSignature());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      for (int i = 0; i < jwks_.size(); i++) {
        output.writeMessage(4, jwks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMessage());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSignature());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      for (int i = 0; i < jwks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, jwks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest)) {
        return super.equals(obj);
      }
      sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest other = (sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest) obj;

      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (hasSignature() != other.hasSignature()) return false;
      if (hasSignature()) {
        if (!getSignature()
            .equals(other.getSignature())) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!getJwksList()
          .equals(other.getJwksList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      if (getJwksCount() > 0) {
        hash = (37 * hash) + JWKS_FIELD_NUMBER;
        hash = (53 * hash) + getJwksList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sui.rpc.v2.VerifySignatureRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sui.rpc.v2.VerifySignatureRequest)
        sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sui.rpc.v2.SignatureVerificationServiceOuterClass.internal_static_sui_rpc_v2_VerifySignatureRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sui.rpc.v2.SignatureVerificationServiceOuterClass.internal_static_sui_rpc_v2_VerifySignatureRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest.class, sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest.Builder.class);
      }

      // Construct using sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
          getSignatureFieldBuilder();
          getJwksFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        message_ = null;
        if (messageBuilder_ != null) {
          messageBuilder_.dispose();
          messageBuilder_ = null;
        }
        signature_ = null;
        if (signatureBuilder_ != null) {
          signatureBuilder_.dispose();
          signatureBuilder_ = null;
        }
        address_ = "";
        if (jwksBuilder_ == null) {
          jwks_ = java.util.Collections.emptyList();
        } else {
          jwks_ = null;
          jwksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sui.rpc.v2.SignatureVerificationServiceOuterClass.internal_static_sui_rpc_v2_VerifySignatureRequest_descriptor;
      }

      @java.lang.Override
      public sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest getDefaultInstanceForType() {
        return sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest.getDefaultInstance();
      }

      @java.lang.Override
      public sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest build() {
        sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest buildPartial() {
        sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest result = new sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest result) {
        if (jwksBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            jwks_ = java.util.Collections.unmodifiableList(jwks_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.jwks_ = jwks_;
        } else {
          result.jwks_ = jwksBuilder_.build();
        }
      }

      private void buildPartial0(sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.message_ = messageBuilder_ == null
              ? message_
              : messageBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.signature_ = signatureBuilder_ == null
              ? signature_
              : signatureBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.address_ = address_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest) {
          return mergeFrom((sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest other) {
        if (other == sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        if (other.hasSignature()) {
          mergeSignature(other.getSignature());
        }
        if (other.hasAddress()) {
          address_ = other.address_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (jwksBuilder_ == null) {
          if (!other.jwks_.isEmpty()) {
            if (jwks_.isEmpty()) {
              jwks_ = other.jwks_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureJwksIsMutable();
              jwks_.addAll(other.jwks_);
            }
            onChanged();
          }
        } else {
          if (!other.jwks_.isEmpty()) {
            if (jwksBuilder_.isEmpty()) {
              jwksBuilder_.dispose();
              jwksBuilder_ = null;
              jwks_ = other.jwks_;
              bitField0_ = (bitField0_ & ~0x00000008);
              jwksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getJwksFieldBuilder() : null;
            } else {
              jwksBuilder_.addAllMessages(other.jwks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMessageFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getSignatureFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                sui.rpc.v2.TransactionOuterClass.ActiveJwk m =
                    input.readMessage(
                        sui.rpc.v2.TransactionOuterClass.ActiveJwk.parser(),
                        extensionRegistry);
                if (jwksBuilder_ == null) {
                  ensureJwksIsMutable();
                  jwks_.add(m);
                } else {
                  jwksBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private sui.rpc.v2.BcsOuterClass.Bcs message_;
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.BcsOuterClass.Bcs, sui.rpc.v2.BcsOuterClass.Bcs.Builder, sui.rpc.v2.BcsOuterClass.BcsOrBuilder> messageBuilder_;
      /**
       * <pre>
       * The message to verify against.
       *
       * Today the only supported message types are `PersonalMessage` and
       * `TransactionData` and the `Bcs.name` must be set to indicate which type of
       * message is being verified.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * The message to verify against.
       *
       * Today the only supported message types are `PersonalMessage` and
       * `TransactionData` and the `Bcs.name` must be set to indicate which type of
       * message is being verified.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
       * @return The message.
       */
      public sui.rpc.v2.BcsOuterClass.Bcs getMessage() {
        if (messageBuilder_ == null) {
          return message_ == null ? sui.rpc.v2.BcsOuterClass.Bcs.getDefaultInstance() : message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The message to verify against.
       *
       * Today the only supported message types are `PersonalMessage` and
       * `TransactionData` and the `Bcs.name` must be set to indicate which type of
       * message is being verified.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
       */
      public Builder setMessage(sui.rpc.v2.BcsOuterClass.Bcs value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
        } else {
          messageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message to verify against.
       *
       * Today the only supported message types are `PersonalMessage` and
       * `TransactionData` and the `Bcs.name` must be set to indicate which type of
       * message is being verified.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
       */
      public Builder setMessage(
          sui.rpc.v2.BcsOuterClass.Bcs.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message to verify against.
       *
       * Today the only supported message types are `PersonalMessage` and
       * `TransactionData` and the `Bcs.name` must be set to indicate which type of
       * message is being verified.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
       */
      public Builder mergeMessage(sui.rpc.v2.BcsOuterClass.Bcs value) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            message_ != null &&
            message_ != sui.rpc.v2.BcsOuterClass.Bcs.getDefaultInstance()) {
            getMessageBuilder().mergeFrom(value);
          } else {
            message_ = value;
          }
        } else {
          messageBuilder_.mergeFrom(value);
        }
        if (message_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The message to verify against.
       *
       * Today the only supported message types are `PersonalMessage` and
       * `TransactionData` and the `Bcs.name` must be set to indicate which type of
       * message is being verified.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = null;
        if (messageBuilder_ != null) {
          messageBuilder_.dispose();
          messageBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message to verify against.
       *
       * Today the only supported message types are `PersonalMessage` and
       * `TransactionData` and the `Bcs.name` must be set to indicate which type of
       * message is being verified.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
       */
      public sui.rpc.v2.BcsOuterClass.Bcs.Builder getMessageBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The message to verify against.
       *
       * Today the only supported message types are `PersonalMessage` and
       * `TransactionData` and the `Bcs.name` must be set to indicate which type of
       * message is being verified.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
       */
      public sui.rpc.v2.BcsOuterClass.BcsOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_ == null ?
              sui.rpc.v2.BcsOuterClass.Bcs.getDefaultInstance() : message_;
        }
      }
      /**
       * <pre>
       * The message to verify against.
       *
       * Today the only supported message types are `PersonalMessage` and
       * `TransactionData` and the `Bcs.name` must be set to indicate which type of
       * message is being verified.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Bcs message = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.BcsOuterClass.Bcs, sui.rpc.v2.BcsOuterClass.Bcs.Builder, sui.rpc.v2.BcsOuterClass.BcsOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sui.rpc.v2.BcsOuterClass.Bcs, sui.rpc.v2.BcsOuterClass.Bcs.Builder, sui.rpc.v2.BcsOuterClass.BcsOrBuilder>(
                  getMessage(),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }

      private sui.rpc.v2.Signature.UserSignature signature_;
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.Signature.UserSignature, sui.rpc.v2.Signature.UserSignature.Builder, sui.rpc.v2.Signature.UserSignatureOrBuilder> signatureBuilder_;
      /**
       * <pre>
       * The signature to verify.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
       * @return Whether the signature field is set.
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The signature to verify.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
       * @return The signature.
       */
      public sui.rpc.v2.Signature.UserSignature getSignature() {
        if (signatureBuilder_ == null) {
          return signature_ == null ? sui.rpc.v2.Signature.UserSignature.getDefaultInstance() : signature_;
        } else {
          return signatureBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The signature to verify.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
       */
      public Builder setSignature(sui.rpc.v2.Signature.UserSignature value) {
        if (signatureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          signature_ = value;
        } else {
          signatureBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The signature to verify.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
       */
      public Builder setSignature(
          sui.rpc.v2.Signature.UserSignature.Builder builderForValue) {
        if (signatureBuilder_ == null) {
          signature_ = builderForValue.build();
        } else {
          signatureBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The signature to verify.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
       */
      public Builder mergeSignature(sui.rpc.v2.Signature.UserSignature value) {
        if (signatureBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            signature_ != null &&
            signature_ != sui.rpc.v2.Signature.UserSignature.getDefaultInstance()) {
            getSignatureBuilder().mergeFrom(value);
          } else {
            signature_ = value;
          }
        } else {
          signatureBuilder_.mergeFrom(value);
        }
        if (signature_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The signature to verify.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = null;
        if (signatureBuilder_ != null) {
          signatureBuilder_.dispose();
          signatureBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The signature to verify.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
       */
      public sui.rpc.v2.Signature.UserSignature.Builder getSignatureBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSignatureFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The signature to verify.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
       */
      public sui.rpc.v2.Signature.UserSignatureOrBuilder getSignatureOrBuilder() {
        if (signatureBuilder_ != null) {
          return signatureBuilder_.getMessageOrBuilder();
        } else {
          return signature_ == null ?
              sui.rpc.v2.Signature.UserSignature.getDefaultInstance() : signature_;
        }
      }
      /**
       * <pre>
       * The signature to verify.
       * </pre>
       *
       * <code>optional .sui.rpc.v2.UserSignature signature = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.Signature.UserSignature, sui.rpc.v2.Signature.UserSignature.Builder, sui.rpc.v2.Signature.UserSignatureOrBuilder> 
          getSignatureFieldBuilder() {
        if (signatureBuilder_ == null) {
          signatureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sui.rpc.v2.Signature.UserSignature, sui.rpc.v2.Signature.UserSignature.Builder, sui.rpc.v2.Signature.UserSignatureOrBuilder>(
                  getSignature(),
                  getParentForChildren(),
                  isClean());
          signature_ = null;
        }
        return signatureBuilder_;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       * Optional. Address to validate against the provided signature.
       *
       * If provided, this address will be compared against the the address derived
       * from the provide signature and a successful response will only be returned
       * if they match.
       * </pre>
       *
       * <code>optional string address = 3;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Optional. Address to validate against the provided signature.
       *
       * If provided, this address will be compared against the the address derived
       * from the provide signature and a successful response will only be returned
       * if they match.
       * </pre>
       *
       * <code>optional string address = 3;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional. Address to validate against the provided signature.
       *
       * If provided, this address will be compared against the the address derived
       * from the provide signature and a successful response will only be returned
       * if they match.
       * </pre>
       *
       * <code>optional string address = 3;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional. Address to validate against the provided signature.
       *
       * If provided, this address will be compared against the the address derived
       * from the provide signature and a successful response will only be returned
       * if they match.
       * </pre>
       *
       * <code>optional string address = 3;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional. Address to validate against the provided signature.
       *
       * If provided, this address will be compared against the the address derived
       * from the provide signature and a successful response will only be returned
       * if they match.
       * </pre>
       *
       * <code>optional string address = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional. Address to validate against the provided signature.
       *
       * If provided, this address will be compared against the the address derived
       * from the provide signature and a successful response will only be returned
       * if they match.
       * </pre>
       *
       * <code>optional string address = 3;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.util.List<sui.rpc.v2.TransactionOuterClass.ActiveJwk> jwks_ =
        java.util.Collections.emptyList();
      private void ensureJwksIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          jwks_ = new java.util.ArrayList<sui.rpc.v2.TransactionOuterClass.ActiveJwk>(jwks_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          sui.rpc.v2.TransactionOuterClass.ActiveJwk, sui.rpc.v2.TransactionOuterClass.ActiveJwk.Builder, sui.rpc.v2.TransactionOuterClass.ActiveJwkOrBuilder> jwksBuilder_;

      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public java.util.List<sui.rpc.v2.TransactionOuterClass.ActiveJwk> getJwksList() {
        if (jwksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(jwks_);
        } else {
          return jwksBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public int getJwksCount() {
        if (jwksBuilder_ == null) {
          return jwks_.size();
        } else {
          return jwksBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public sui.rpc.v2.TransactionOuterClass.ActiveJwk getJwks(int index) {
        if (jwksBuilder_ == null) {
          return jwks_.get(index);
        } else {
          return jwksBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public Builder setJwks(
          int index, sui.rpc.v2.TransactionOuterClass.ActiveJwk value) {
        if (jwksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJwksIsMutable();
          jwks_.set(index, value);
          onChanged();
        } else {
          jwksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public Builder setJwks(
          int index, sui.rpc.v2.TransactionOuterClass.ActiveJwk.Builder builderForValue) {
        if (jwksBuilder_ == null) {
          ensureJwksIsMutable();
          jwks_.set(index, builderForValue.build());
          onChanged();
        } else {
          jwksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public Builder addJwks(sui.rpc.v2.TransactionOuterClass.ActiveJwk value) {
        if (jwksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJwksIsMutable();
          jwks_.add(value);
          onChanged();
        } else {
          jwksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public Builder addJwks(
          int index, sui.rpc.v2.TransactionOuterClass.ActiveJwk value) {
        if (jwksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJwksIsMutable();
          jwks_.add(index, value);
          onChanged();
        } else {
          jwksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public Builder addJwks(
          sui.rpc.v2.TransactionOuterClass.ActiveJwk.Builder builderForValue) {
        if (jwksBuilder_ == null) {
          ensureJwksIsMutable();
          jwks_.add(builderForValue.build());
          onChanged();
        } else {
          jwksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public Builder addJwks(
          int index, sui.rpc.v2.TransactionOuterClass.ActiveJwk.Builder builderForValue) {
        if (jwksBuilder_ == null) {
          ensureJwksIsMutable();
          jwks_.add(index, builderForValue.build());
          onChanged();
        } else {
          jwksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public Builder addAllJwks(
          java.lang.Iterable<? extends sui.rpc.v2.TransactionOuterClass.ActiveJwk> values) {
        if (jwksBuilder_ == null) {
          ensureJwksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, jwks_);
          onChanged();
        } else {
          jwksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public Builder clearJwks() {
        if (jwksBuilder_ == null) {
          jwks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          jwksBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public Builder removeJwks(int index) {
        if (jwksBuilder_ == null) {
          ensureJwksIsMutable();
          jwks_.remove(index);
          onChanged();
        } else {
          jwksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public sui.rpc.v2.TransactionOuterClass.ActiveJwk.Builder getJwksBuilder(
          int index) {
        return getJwksFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public sui.rpc.v2.TransactionOuterClass.ActiveJwkOrBuilder getJwksOrBuilder(
          int index) {
        if (jwksBuilder_ == null) {
          return jwks_.get(index);  } else {
          return jwksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public java.util.List<? extends sui.rpc.v2.TransactionOuterClass.ActiveJwkOrBuilder> 
           getJwksOrBuilderList() {
        if (jwksBuilder_ != null) {
          return jwksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(jwks_);
        }
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public sui.rpc.v2.TransactionOuterClass.ActiveJwk.Builder addJwksBuilder() {
        return getJwksFieldBuilder().addBuilder(
            sui.rpc.v2.TransactionOuterClass.ActiveJwk.getDefaultInstance());
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public sui.rpc.v2.TransactionOuterClass.ActiveJwk.Builder addJwksBuilder(
          int index) {
        return getJwksFieldBuilder().addBuilder(
            index, sui.rpc.v2.TransactionOuterClass.ActiveJwk.getDefaultInstance());
      }
      /**
       * <pre>
       * The set of JWKs to use when verifying Zklogin signatures.
       * If this is empty the current set of valid JWKs stored onchain will be used
       * </pre>
       *
       * <code>repeated .sui.rpc.v2.ActiveJwk jwks = 4;</code>
       */
      public java.util.List<sui.rpc.v2.TransactionOuterClass.ActiveJwk.Builder> 
           getJwksBuilderList() {
        return getJwksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          sui.rpc.v2.TransactionOuterClass.ActiveJwk, sui.rpc.v2.TransactionOuterClass.ActiveJwk.Builder, sui.rpc.v2.TransactionOuterClass.ActiveJwkOrBuilder> 
          getJwksFieldBuilder() {
        if (jwksBuilder_ == null) {
          jwksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              sui.rpc.v2.TransactionOuterClass.ActiveJwk, sui.rpc.v2.TransactionOuterClass.ActiveJwk.Builder, sui.rpc.v2.TransactionOuterClass.ActiveJwkOrBuilder>(
                  jwks_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          jwks_ = null;
        }
        return jwksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sui.rpc.v2.VerifySignatureRequest)
    }

    // @@protoc_insertion_point(class_scope:sui.rpc.v2.VerifySignatureRequest)
    private static final sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest();
    }

    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VerifySignatureRequest>
        PARSER = new com.google.protobuf.AbstractParser<VerifySignatureRequest>() {
      @java.lang.Override
      public VerifySignatureRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VerifySignatureRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VerifySignatureRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VerifySignatureResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sui.rpc.v2.VerifySignatureResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Indicates if the provided signature was valid given the requested parameters.
     * </pre>
     *
     * <code>optional bool is_valid = 1;</code>
     * @return Whether the isValid field is set.
     */
    boolean hasIsValid();
    /**
     * <pre>
     * Indicates if the provided signature was valid given the requested parameters.
     * </pre>
     *
     * <code>optional bool is_valid = 1;</code>
     * @return The isValid.
     */
    boolean getIsValid();

    /**
     * <pre>
     * If `is_valid` is `false`, this is the reason for why the signature verification failed.
     * </pre>
     *
     * <code>optional string reason = 2;</code>
     * @return Whether the reason field is set.
     */
    boolean hasReason();
    /**
     * <pre>
     * If `is_valid` is `false`, this is the reason for why the signature verification failed.
     * </pre>
     *
     * <code>optional string reason = 2;</code>
     * @return The reason.
     */
    java.lang.String getReason();
    /**
     * <pre>
     * If `is_valid` is `false`, this is the reason for why the signature verification failed.
     * </pre>
     *
     * <code>optional string reason = 2;</code>
     * @return The bytes for reason.
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * Protobuf type {@code sui.rpc.v2.VerifySignatureResponse}
   */
  public static final class VerifySignatureResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sui.rpc.v2.VerifySignatureResponse)
      VerifySignatureResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VerifySignatureResponse.newBuilder() to construct.
    private VerifySignatureResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VerifySignatureResponse() {
      reason_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VerifySignatureResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sui.rpc.v2.SignatureVerificationServiceOuterClass.internal_static_sui_rpc_v2_VerifySignatureResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sui.rpc.v2.SignatureVerificationServiceOuterClass.internal_static_sui_rpc_v2_VerifySignatureResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse.class, sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse.Builder.class);
    }

    private int bitField0_;
    public static final int IS_VALID_FIELD_NUMBER = 1;
    private boolean isValid_ = false;
    /**
     * <pre>
     * Indicates if the provided signature was valid given the requested parameters.
     * </pre>
     *
     * <code>optional bool is_valid = 1;</code>
     * @return Whether the isValid field is set.
     */
    @java.lang.Override
    public boolean hasIsValid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Indicates if the provided signature was valid given the requested parameters.
     * </pre>
     *
     * <code>optional bool is_valid = 1;</code>
     * @return The isValid.
     */
    @java.lang.Override
    public boolean getIsValid() {
      return isValid_;
    }

    public static final int REASON_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object reason_ = "";
    /**
     * <pre>
     * If `is_valid` is `false`, this is the reason for why the signature verification failed.
     * </pre>
     *
     * <code>optional string reason = 2;</code>
     * @return Whether the reason field is set.
     */
    @java.lang.Override
    public boolean hasReason() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * If `is_valid` is `false`, this is the reason for why the signature verification failed.
     * </pre>
     *
     * <code>optional string reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * If `is_valid` is `false`, this is the reason for why the signature verification failed.
     * </pre>
     *
     * <code>optional string reason = 2;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, isValid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reason_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isValid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reason_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse)) {
        return super.equals(obj);
      }
      sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse other = (sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse) obj;

      if (hasIsValid() != other.hasIsValid()) return false;
      if (hasIsValid()) {
        if (getIsValid()
            != other.getIsValid()) return false;
      }
      if (hasReason() != other.hasReason()) return false;
      if (hasReason()) {
        if (!getReason()
            .equals(other.getReason())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsValid()) {
        hash = (37 * hash) + IS_VALID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsValid());
      }
      if (hasReason()) {
        hash = (37 * hash) + REASON_FIELD_NUMBER;
        hash = (53 * hash) + getReason().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sui.rpc.v2.VerifySignatureResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sui.rpc.v2.VerifySignatureResponse)
        sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sui.rpc.v2.SignatureVerificationServiceOuterClass.internal_static_sui_rpc_v2_VerifySignatureResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sui.rpc.v2.SignatureVerificationServiceOuterClass.internal_static_sui_rpc_v2_VerifySignatureResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse.class, sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse.Builder.class);
      }

      // Construct using sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        isValid_ = false;
        reason_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sui.rpc.v2.SignatureVerificationServiceOuterClass.internal_static_sui_rpc_v2_VerifySignatureResponse_descriptor;
      }

      @java.lang.Override
      public sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse getDefaultInstanceForType() {
        return sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse.getDefaultInstance();
      }

      @java.lang.Override
      public sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse build() {
        sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse buildPartial() {
        sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse result = new sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isValid_ = isValid_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.reason_ = reason_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse) {
          return mergeFrom((sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse other) {
        if (other == sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse.getDefaultInstance()) return this;
        if (other.hasIsValid()) {
          setIsValid(other.getIsValid());
        }
        if (other.hasReason()) {
          reason_ = other.reason_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                isValid_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                reason_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean isValid_ ;
      /**
       * <pre>
       * Indicates if the provided signature was valid given the requested parameters.
       * </pre>
       *
       * <code>optional bool is_valid = 1;</code>
       * @return Whether the isValid field is set.
       */
      @java.lang.Override
      public boolean hasIsValid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Indicates if the provided signature was valid given the requested parameters.
       * </pre>
       *
       * <code>optional bool is_valid = 1;</code>
       * @return The isValid.
       */
      @java.lang.Override
      public boolean getIsValid() {
        return isValid_;
      }
      /**
       * <pre>
       * Indicates if the provided signature was valid given the requested parameters.
       * </pre>
       *
       * <code>optional bool is_valid = 1;</code>
       * @param value The isValid to set.
       * @return This builder for chaining.
       */
      public Builder setIsValid(boolean value) {

        isValid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Indicates if the provided signature was valid given the requested parameters.
       * </pre>
       *
       * <code>optional bool is_valid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsValid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isValid_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object reason_ = "";
      /**
       * <pre>
       * If `is_valid` is `false`, this is the reason for why the signature verification failed.
       * </pre>
       *
       * <code>optional string reason = 2;</code>
       * @return Whether the reason field is set.
       */
      public boolean hasReason() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * If `is_valid` is `false`, this is the reason for why the signature verification failed.
       * </pre>
       *
       * <code>optional string reason = 2;</code>
       * @return The reason.
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * If `is_valid` is `false`, this is the reason for why the signature verification failed.
       * </pre>
       *
       * <code>optional string reason = 2;</code>
       * @return The bytes for reason.
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * If `is_valid` is `false`, this is the reason for why the signature verification failed.
       * </pre>
       *
       * <code>optional string reason = 2;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        reason_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If `is_valid` is `false`, this is the reason for why the signature verification failed.
       * </pre>
       *
       * <code>optional string reason = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        reason_ = getDefaultInstance().getReason();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If `is_valid` is `false`, this is the reason for why the signature verification failed.
       * </pre>
       *
       * <code>optional string reason = 2;</code>
       * @param value The bytes for reason to set.
       * @return This builder for chaining.
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        reason_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sui.rpc.v2.VerifySignatureResponse)
    }

    // @@protoc_insertion_point(class_scope:sui.rpc.v2.VerifySignatureResponse)
    private static final sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse();
    }

    public static sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VerifySignatureResponse>
        PARSER = new com.google.protobuf.AbstractParser<VerifySignatureResponse>() {
      @java.lang.Override
      public VerifySignatureResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VerifySignatureResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VerifySignatureResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sui.rpc.v2.SignatureVerificationServiceOuterClass.VerifySignatureResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sui_rpc_v2_VerifySignatureRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sui_rpc_v2_VerifySignatureRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sui_rpc_v2_VerifySignatureResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sui_rpc_v2_VerifySignatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/sui/rpc/v2/signature_verification_serv" +
      "ice.proto\022\nsui.rpc.v2\032\024sui/rpc/v2/bcs.pr" +
      "oto\032\032sui/rpc/v2/signature.proto\032\034sui/rpc" +
      "/v2/transaction.proto\"\323\001\n\026VerifySignatur" +
      "eRequest\022%\n\007message\030\001 \001(\0132\017.sui.rpc.v2.B" +
      "csH\000\210\001\001\0221\n\tsignature\030\002 \001(\0132\031.sui.rpc.v2." +
      "UserSignatureH\001\210\001\001\022\024\n\007address\030\003 \001(\tH\002\210\001\001" +
      "\022#\n\004jwks\030\004 \003(\0132\025.sui.rpc.v2.ActiveJwkB\n\n" +
      "\010_messageB\014\n\n_signatureB\n\n\010_address\"]\n\027V" +
      "erifySignatureResponse\022\025\n\010is_valid\030\001 \001(\010" +
      "H\000\210\001\001\022\023\n\006reason\030\002 \001(\tH\001\210\001\001B\013\n\t_is_validB" +
      "\t\n\007_reason2z\n\034SignatureVerificationServi" +
      "ce\022Z\n\017VerifySignature\022\".sui.rpc.v2.Verif" +
      "ySignatureRequest\032#.sui.rpc.v2.VerifySig" +
      "natureResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sui.rpc.v2.BcsOuterClass.getDescriptor(),
          sui.rpc.v2.Signature.getDescriptor(),
          sui.rpc.v2.TransactionOuterClass.getDescriptor(),
        });
    internal_static_sui_rpc_v2_VerifySignatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sui_rpc_v2_VerifySignatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sui_rpc_v2_VerifySignatureRequest_descriptor,
        new java.lang.String[] { "Message", "Signature", "Address", "Jwks", });
    internal_static_sui_rpc_v2_VerifySignatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sui_rpc_v2_VerifySignatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sui_rpc_v2_VerifySignatureResponse_descriptor,
        new java.lang.String[] { "IsValid", "Reason", });
    sui.rpc.v2.BcsOuterClass.getDescriptor();
    sui.rpc.v2.Signature.getDescriptor();
    sui.rpc.v2.TransactionOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
