// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sui/rpc/v2/subscription_service.proto

// Protobuf Java Version: 3.25.3
package sui.rpc.v2;

public final class SubscriptionServiceOuterClass {
  private SubscriptionServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscribeCheckpointsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sui.rpc.v2.SubscribeCheckpointsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Optional. Mask for specifying which parts of the
     * SubscribeCheckpointsResponse should be returned.
     * </pre>
     *
     * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
     * @return Whether the readMask field is set.
     */
    boolean hasReadMask();
    /**
     * <pre>
     * Optional. Mask for specifying which parts of the
     * SubscribeCheckpointsResponse should be returned.
     * </pre>
     *
     * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
     * @return The readMask.
     */
    com.google.protobuf.FieldMask getReadMask();
    /**
     * <pre>
     * Optional. Mask for specifying which parts of the
     * SubscribeCheckpointsResponse should be returned.
     * </pre>
     *
     * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
     */
    com.google.protobuf.FieldMaskOrBuilder getReadMaskOrBuilder();
  }
  /**
   * <pre>
   * Request message for SubscriptionService.SubscribeCheckpoints
   * </pre>
   *
   * Protobuf type {@code sui.rpc.v2.SubscribeCheckpointsRequest}
   */
  public static final class SubscribeCheckpointsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sui.rpc.v2.SubscribeCheckpointsRequest)
      SubscribeCheckpointsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubscribeCheckpointsRequest.newBuilder() to construct.
    private SubscribeCheckpointsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscribeCheckpointsRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SubscribeCheckpointsRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sui.rpc.v2.SubscriptionServiceOuterClass.internal_static_sui_rpc_v2_SubscribeCheckpointsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sui.rpc.v2.SubscriptionServiceOuterClass.internal_static_sui_rpc_v2_SubscribeCheckpointsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest.class, sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest.Builder.class);
    }

    private int bitField0_;
    public static final int READ_MASK_FIELD_NUMBER = 1;
    private com.google.protobuf.FieldMask readMask_;
    /**
     * <pre>
     * Optional. Mask for specifying which parts of the
     * SubscribeCheckpointsResponse should be returned.
     * </pre>
     *
     * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
     * @return Whether the readMask field is set.
     */
    @java.lang.Override
    public boolean hasReadMask() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Optional. Mask for specifying which parts of the
     * SubscribeCheckpointsResponse should be returned.
     * </pre>
     *
     * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
     * @return The readMask.
     */
    @java.lang.Override
    public com.google.protobuf.FieldMask getReadMask() {
      return readMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : readMask_;
    }
    /**
     * <pre>
     * Optional. Mask for specifying which parts of the
     * SubscribeCheckpointsResponse should be returned.
     * </pre>
     *
     * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.FieldMaskOrBuilder getReadMaskOrBuilder() {
      return readMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : readMask_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getReadMask());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getReadMask());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest)) {
        return super.equals(obj);
      }
      sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest other = (sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest) obj;

      if (hasReadMask() != other.hasReadMask()) return false;
      if (hasReadMask()) {
        if (!getReadMask()
            .equals(other.getReadMask())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReadMask()) {
        hash = (37 * hash) + READ_MASK_FIELD_NUMBER;
        hash = (53 * hash) + getReadMask().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Request message for SubscriptionService.SubscribeCheckpoints
     * </pre>
     *
     * Protobuf type {@code sui.rpc.v2.SubscribeCheckpointsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sui.rpc.v2.SubscribeCheckpointsRequest)
        sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sui.rpc.v2.SubscriptionServiceOuterClass.internal_static_sui_rpc_v2_SubscribeCheckpointsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sui.rpc.v2.SubscriptionServiceOuterClass.internal_static_sui_rpc_v2_SubscribeCheckpointsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest.class, sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest.Builder.class);
      }

      // Construct using sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getReadMaskFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        readMask_ = null;
        if (readMaskBuilder_ != null) {
          readMaskBuilder_.dispose();
          readMaskBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sui.rpc.v2.SubscriptionServiceOuterClass.internal_static_sui_rpc_v2_SubscribeCheckpointsRequest_descriptor;
      }

      @java.lang.Override
      public sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest getDefaultInstanceForType() {
        return sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest build() {
        sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest buildPartial() {
        sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest result = new sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.readMask_ = readMaskBuilder_ == null
              ? readMask_
              : readMaskBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest) {
          return mergeFrom((sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest other) {
        if (other == sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest.getDefaultInstance()) return this;
        if (other.hasReadMask()) {
          mergeReadMask(other.getReadMask());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getReadMaskFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.FieldMask readMask_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> readMaskBuilder_;
      /**
       * <pre>
       * Optional. Mask for specifying which parts of the
       * SubscribeCheckpointsResponse should be returned.
       * </pre>
       *
       * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
       * @return Whether the readMask field is set.
       */
      public boolean hasReadMask() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Optional. Mask for specifying which parts of the
       * SubscribeCheckpointsResponse should be returned.
       * </pre>
       *
       * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
       * @return The readMask.
       */
      public com.google.protobuf.FieldMask getReadMask() {
        if (readMaskBuilder_ == null) {
          return readMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : readMask_;
        } else {
          return readMaskBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Optional. Mask for specifying which parts of the
       * SubscribeCheckpointsResponse should be returned.
       * </pre>
       *
       * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
       */
      public Builder setReadMask(com.google.protobuf.FieldMask value) {
        if (readMaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          readMask_ = value;
        } else {
          readMaskBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional. Mask for specifying which parts of the
       * SubscribeCheckpointsResponse should be returned.
       * </pre>
       *
       * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
       */
      public Builder setReadMask(
          com.google.protobuf.FieldMask.Builder builderForValue) {
        if (readMaskBuilder_ == null) {
          readMask_ = builderForValue.build();
        } else {
          readMaskBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional. Mask for specifying which parts of the
       * SubscribeCheckpointsResponse should be returned.
       * </pre>
       *
       * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
       */
      public Builder mergeReadMask(com.google.protobuf.FieldMask value) {
        if (readMaskBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            readMask_ != null &&
            readMask_ != com.google.protobuf.FieldMask.getDefaultInstance()) {
            getReadMaskBuilder().mergeFrom(value);
          } else {
            readMask_ = value;
          }
        } else {
          readMaskBuilder_.mergeFrom(value);
        }
        if (readMask_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Optional. Mask for specifying which parts of the
       * SubscribeCheckpointsResponse should be returned.
       * </pre>
       *
       * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
       */
      public Builder clearReadMask() {
        bitField0_ = (bitField0_ & ~0x00000001);
        readMask_ = null;
        if (readMaskBuilder_ != null) {
          readMaskBuilder_.dispose();
          readMaskBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional. Mask for specifying which parts of the
       * SubscribeCheckpointsResponse should be returned.
       * </pre>
       *
       * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
       */
      public com.google.protobuf.FieldMask.Builder getReadMaskBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getReadMaskFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Optional. Mask for specifying which parts of the
       * SubscribeCheckpointsResponse should be returned.
       * </pre>
       *
       * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
       */
      public com.google.protobuf.FieldMaskOrBuilder getReadMaskOrBuilder() {
        if (readMaskBuilder_ != null) {
          return readMaskBuilder_.getMessageOrBuilder();
        } else {
          return readMask_ == null ?
              com.google.protobuf.FieldMask.getDefaultInstance() : readMask_;
        }
      }
      /**
       * <pre>
       * Optional. Mask for specifying which parts of the
       * SubscribeCheckpointsResponse should be returned.
       * </pre>
       *
       * <code>optional .google.protobuf.FieldMask read_mask = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
          getReadMaskFieldBuilder() {
        if (readMaskBuilder_ == null) {
          readMaskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                  getReadMask(),
                  getParentForChildren(),
                  isClean());
          readMask_ = null;
        }
        return readMaskBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sui.rpc.v2.SubscribeCheckpointsRequest)
    }

    // @@protoc_insertion_point(class_scope:sui.rpc.v2.SubscribeCheckpointsRequest)
    private static final sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest();
    }

    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscribeCheckpointsRequest>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeCheckpointsRequest>() {
      @java.lang.Override
      public SubscribeCheckpointsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SubscribeCheckpointsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubscribeCheckpointsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubscribeCheckpointsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sui.rpc.v2.SubscribeCheckpointsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Required. The checkpoint sequence number and value of the current cursor
     * into the checkpoint stream
     * </pre>
     *
     * <code>optional uint64 cursor = 1;</code>
     * @return Whether the cursor field is set.
     */
    boolean hasCursor();
    /**
     * <pre>
     * Required. The checkpoint sequence number and value of the current cursor
     * into the checkpoint stream
     * </pre>
     *
     * <code>optional uint64 cursor = 1;</code>
     * @return The cursor.
     */
    long getCursor();

    /**
     * <pre>
     * The requested data for this checkpoint
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
     * @return Whether the checkpoint field is set.
     */
    boolean hasCheckpoint();
    /**
     * <pre>
     * The requested data for this checkpoint
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
     * @return The checkpoint.
     */
    sui.rpc.v2.CheckpointOuterClass.Checkpoint getCheckpoint();
    /**
     * <pre>
     * The requested data for this checkpoint
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
     */
    sui.rpc.v2.CheckpointOuterClass.CheckpointOrBuilder getCheckpointOrBuilder();
  }
  /**
   * <pre>
   * Response message for SubscriptionService.SubscribeCheckpoints
   * </pre>
   *
   * Protobuf type {@code sui.rpc.v2.SubscribeCheckpointsResponse}
   */
  public static final class SubscribeCheckpointsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sui.rpc.v2.SubscribeCheckpointsResponse)
      SubscribeCheckpointsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubscribeCheckpointsResponse.newBuilder() to construct.
    private SubscribeCheckpointsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscribeCheckpointsResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SubscribeCheckpointsResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sui.rpc.v2.SubscriptionServiceOuterClass.internal_static_sui_rpc_v2_SubscribeCheckpointsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sui.rpc.v2.SubscriptionServiceOuterClass.internal_static_sui_rpc_v2_SubscribeCheckpointsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse.class, sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse.Builder.class);
    }

    private int bitField0_;
    public static final int CURSOR_FIELD_NUMBER = 1;
    private long cursor_ = 0L;
    /**
     * <pre>
     * Required. The checkpoint sequence number and value of the current cursor
     * into the checkpoint stream
     * </pre>
     *
     * <code>optional uint64 cursor = 1;</code>
     * @return Whether the cursor field is set.
     */
    @java.lang.Override
    public boolean hasCursor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Required. The checkpoint sequence number and value of the current cursor
     * into the checkpoint stream
     * </pre>
     *
     * <code>optional uint64 cursor = 1;</code>
     * @return The cursor.
     */
    @java.lang.Override
    public long getCursor() {
      return cursor_;
    }

    public static final int CHECKPOINT_FIELD_NUMBER = 2;
    private sui.rpc.v2.CheckpointOuterClass.Checkpoint checkpoint_;
    /**
     * <pre>
     * The requested data for this checkpoint
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
     * @return Whether the checkpoint field is set.
     */
    @java.lang.Override
    public boolean hasCheckpoint() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The requested data for this checkpoint
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
     * @return The checkpoint.
     */
    @java.lang.Override
    public sui.rpc.v2.CheckpointOuterClass.Checkpoint getCheckpoint() {
      return checkpoint_ == null ? sui.rpc.v2.CheckpointOuterClass.Checkpoint.getDefaultInstance() : checkpoint_;
    }
    /**
     * <pre>
     * The requested data for this checkpoint
     * </pre>
     *
     * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
     */
    @java.lang.Override
    public sui.rpc.v2.CheckpointOuterClass.CheckpointOrBuilder getCheckpointOrBuilder() {
      return checkpoint_ == null ? sui.rpc.v2.CheckpointOuterClass.Checkpoint.getDefaultInstance() : checkpoint_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, cursor_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getCheckpoint());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, cursor_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCheckpoint());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse)) {
        return super.equals(obj);
      }
      sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse other = (sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse) obj;

      if (hasCursor() != other.hasCursor()) return false;
      if (hasCursor()) {
        if (getCursor()
            != other.getCursor()) return false;
      }
      if (hasCheckpoint() != other.hasCheckpoint()) return false;
      if (hasCheckpoint()) {
        if (!getCheckpoint()
            .equals(other.getCheckpoint())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCursor()) {
        hash = (37 * hash) + CURSOR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCursor());
      }
      if (hasCheckpoint()) {
        hash = (37 * hash) + CHECKPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getCheckpoint().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response message for SubscriptionService.SubscribeCheckpoints
     * </pre>
     *
     * Protobuf type {@code sui.rpc.v2.SubscribeCheckpointsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sui.rpc.v2.SubscribeCheckpointsResponse)
        sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sui.rpc.v2.SubscriptionServiceOuterClass.internal_static_sui_rpc_v2_SubscribeCheckpointsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sui.rpc.v2.SubscriptionServiceOuterClass.internal_static_sui_rpc_v2_SubscribeCheckpointsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse.class, sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse.Builder.class);
      }

      // Construct using sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCheckpointFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cursor_ = 0L;
        checkpoint_ = null;
        if (checkpointBuilder_ != null) {
          checkpointBuilder_.dispose();
          checkpointBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sui.rpc.v2.SubscriptionServiceOuterClass.internal_static_sui_rpc_v2_SubscribeCheckpointsResponse_descriptor;
      }

      @java.lang.Override
      public sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse getDefaultInstanceForType() {
        return sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse build() {
        sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse buildPartial() {
        sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse result = new sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cursor_ = cursor_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.checkpoint_ = checkpointBuilder_ == null
              ? checkpoint_
              : checkpointBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse) {
          return mergeFrom((sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse other) {
        if (other == sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse.getDefaultInstance()) return this;
        if (other.hasCursor()) {
          setCursor(other.getCursor());
        }
        if (other.hasCheckpoint()) {
          mergeCheckpoint(other.getCheckpoint());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cursor_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getCheckpointFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long cursor_ ;
      /**
       * <pre>
       * Required. The checkpoint sequence number and value of the current cursor
       * into the checkpoint stream
       * </pre>
       *
       * <code>optional uint64 cursor = 1;</code>
       * @return Whether the cursor field is set.
       */
      @java.lang.Override
      public boolean hasCursor() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Required. The checkpoint sequence number and value of the current cursor
       * into the checkpoint stream
       * </pre>
       *
       * <code>optional uint64 cursor = 1;</code>
       * @return The cursor.
       */
      @java.lang.Override
      public long getCursor() {
        return cursor_;
      }
      /**
       * <pre>
       * Required. The checkpoint sequence number and value of the current cursor
       * into the checkpoint stream
       * </pre>
       *
       * <code>optional uint64 cursor = 1;</code>
       * @param value The cursor to set.
       * @return This builder for chaining.
       */
      public Builder setCursor(long value) {

        cursor_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Required. The checkpoint sequence number and value of the current cursor
       * into the checkpoint stream
       * </pre>
       *
       * <code>optional uint64 cursor = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCursor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cursor_ = 0L;
        onChanged();
        return this;
      }

      private sui.rpc.v2.CheckpointOuterClass.Checkpoint checkpoint_;
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.CheckpointOuterClass.Checkpoint, sui.rpc.v2.CheckpointOuterClass.Checkpoint.Builder, sui.rpc.v2.CheckpointOuterClass.CheckpointOrBuilder> checkpointBuilder_;
      /**
       * <pre>
       * The requested data for this checkpoint
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
       * @return Whether the checkpoint field is set.
       */
      public boolean hasCheckpoint() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The requested data for this checkpoint
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
       * @return The checkpoint.
       */
      public sui.rpc.v2.CheckpointOuterClass.Checkpoint getCheckpoint() {
        if (checkpointBuilder_ == null) {
          return checkpoint_ == null ? sui.rpc.v2.CheckpointOuterClass.Checkpoint.getDefaultInstance() : checkpoint_;
        } else {
          return checkpointBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The requested data for this checkpoint
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
       */
      public Builder setCheckpoint(sui.rpc.v2.CheckpointOuterClass.Checkpoint value) {
        if (checkpointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          checkpoint_ = value;
        } else {
          checkpointBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The requested data for this checkpoint
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
       */
      public Builder setCheckpoint(
          sui.rpc.v2.CheckpointOuterClass.Checkpoint.Builder builderForValue) {
        if (checkpointBuilder_ == null) {
          checkpoint_ = builderForValue.build();
        } else {
          checkpointBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The requested data for this checkpoint
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
       */
      public Builder mergeCheckpoint(sui.rpc.v2.CheckpointOuterClass.Checkpoint value) {
        if (checkpointBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            checkpoint_ != null &&
            checkpoint_ != sui.rpc.v2.CheckpointOuterClass.Checkpoint.getDefaultInstance()) {
            getCheckpointBuilder().mergeFrom(value);
          } else {
            checkpoint_ = value;
          }
        } else {
          checkpointBuilder_.mergeFrom(value);
        }
        if (checkpoint_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The requested data for this checkpoint
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
       */
      public Builder clearCheckpoint() {
        bitField0_ = (bitField0_ & ~0x00000002);
        checkpoint_ = null;
        if (checkpointBuilder_ != null) {
          checkpointBuilder_.dispose();
          checkpointBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The requested data for this checkpoint
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
       */
      public sui.rpc.v2.CheckpointOuterClass.Checkpoint.Builder getCheckpointBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCheckpointFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The requested data for this checkpoint
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
       */
      public sui.rpc.v2.CheckpointOuterClass.CheckpointOrBuilder getCheckpointOrBuilder() {
        if (checkpointBuilder_ != null) {
          return checkpointBuilder_.getMessageOrBuilder();
        } else {
          return checkpoint_ == null ?
              sui.rpc.v2.CheckpointOuterClass.Checkpoint.getDefaultInstance() : checkpoint_;
        }
      }
      /**
       * <pre>
       * The requested data for this checkpoint
       * </pre>
       *
       * <code>optional .sui.rpc.v2.Checkpoint checkpoint = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sui.rpc.v2.CheckpointOuterClass.Checkpoint, sui.rpc.v2.CheckpointOuterClass.Checkpoint.Builder, sui.rpc.v2.CheckpointOuterClass.CheckpointOrBuilder> 
          getCheckpointFieldBuilder() {
        if (checkpointBuilder_ == null) {
          checkpointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sui.rpc.v2.CheckpointOuterClass.Checkpoint, sui.rpc.v2.CheckpointOuterClass.Checkpoint.Builder, sui.rpc.v2.CheckpointOuterClass.CheckpointOrBuilder>(
                  getCheckpoint(),
                  getParentForChildren(),
                  isClean());
          checkpoint_ = null;
        }
        return checkpointBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sui.rpc.v2.SubscribeCheckpointsResponse)
    }

    // @@protoc_insertion_point(class_scope:sui.rpc.v2.SubscribeCheckpointsResponse)
    private static final sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse();
    }

    public static sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscribeCheckpointsResponse>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeCheckpointsResponse>() {
      @java.lang.Override
      public SubscribeCheckpointsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SubscribeCheckpointsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubscribeCheckpointsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sui.rpc.v2.SubscriptionServiceOuterClass.SubscribeCheckpointsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sui_rpc_v2_SubscribeCheckpointsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sui_rpc_v2_SubscribeCheckpointsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sui_rpc_v2_SubscribeCheckpointsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sui_rpc_v2_SubscribeCheckpointsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%sui/rpc/v2/subscription_service.proto\022" +
      "\nsui.rpc.v2\032 google/protobuf/field_mask." +
      "proto\032\033sui/rpc/v2/checkpoint.proto\"_\n\033Su" +
      "bscribeCheckpointsRequest\0222\n\tread_mask\030\001" +
      " \001(\0132\032.google.protobuf.FieldMaskH\000\210\001\001B\014\n" +
      "\n_read_mask\"~\n\034SubscribeCheckpointsRespo" +
      "nse\022\023\n\006cursor\030\001 \001(\004H\000\210\001\001\022/\n\ncheckpoint\030\002" +
      " \001(\0132\026.sui.rpc.v2.CheckpointH\001\210\001\001B\t\n\007_cu" +
      "rsorB\r\n\013_checkpoint2\202\001\n\023SubscriptionServ" +
      "ice\022k\n\024SubscribeCheckpoints\022\'.sui.rpc.v2" +
      ".SubscribeCheckpointsRequest\032(.sui.rpc.v" +
      "2.SubscribeCheckpointsResponse0\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          sui.rpc.v2.CheckpointOuterClass.getDescriptor(),
        });
    internal_static_sui_rpc_v2_SubscribeCheckpointsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sui_rpc_v2_SubscribeCheckpointsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sui_rpc_v2_SubscribeCheckpointsRequest_descriptor,
        new java.lang.String[] { "ReadMask", });
    internal_static_sui_rpc_v2_SubscribeCheckpointsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sui_rpc_v2_SubscribeCheckpointsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sui_rpc_v2_SubscribeCheckpointsResponse_descriptor,
        new java.lang.String[] { "Cursor", "Checkpoint", });
    com.google.protobuf.FieldMaskProto.getDescriptor();
    sui.rpc.v2.CheckpointOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
